// (c) 2018-2023 OtherSide Entertainment, Inc
// SPDX-License-Identifier: MIT

#include "WorldMap/TATWorldMapSubsystem.h"

// tat
#include "Developer/TATProjectSettings.h"
#include "GameFramework/TATWorldSettings.h"
#include "WorldMap/TATMapActorComponent.h"
#include "WorldMap/TATWorldMapBoundary.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(TATWorldMapSubsystem)

DEFINE_LOG_CATEGORY_STATIC(LogTATWorldMapSubsystem, Log, All);

bool UTATWorldMapSubsystem::ShouldCreateSubsystem(UObject* outer) const
{
   if (!Super::ShouldCreateSubsystem(outer))
   {
      return false;
   }

   if (const UWorld* world = outer->GetWorld())
   {
      if (!world->IsGameWorld())
      {
         return false;
      }

      if (const UGameInstance* gameInstance = world->GetGameInstance())
      {
         if (gameInstance->IsDedicatedServerInstance())
         {
            return false;
         }
      }
   }

   return true;
}

int32 UTATWorldMapSubsystem::GetNumMaps() const
{
   return _registeredMaps.Num();
}

ATATWorldMapBoundary* UTATWorldMapSubsystem::GetMapBoundaryActor(int32 mapIndex) const
{
   return _registeredMaps.IsValidIndex(mapIndex) ? _registeredMaps[mapIndex].BoundaryActor.Get() : nullptr;
}

ATATWorldMapBoundary* UTATWorldMapSubsystem::GetCurrentWorldMapBoundaryActor() const
{
   return _GetCurrentWorldMapBoundaryActor();
}

FText UTATWorldMapSubsystem::GetMapLabel(int32 mapIndex) const
{
   return _registeredMaps.IsValidIndex(mapIndex) ? _registeredMaps[mapIndex].Label : FText::GetEmpty();
}

int32 UTATWorldMapSubsystem::GetCurrentMapIndex() const
{
   return (_activeMapIndexOverride != INDEX_NONE) ? _activeMapIndexOverride : GetMapIndexForCurrentPlayerLocation();
}

int32 UTATWorldMapSubsystem::GetMapIndexForCurrentPlayerLocation() const
{
   return !_activeMapStack.IsEmpty() ? _activeMapStack.Last() : _primaryMapIndex;
}

bool UTATWorldMapSubsystem::GetMapIndexOverride(int32& overrideIndex) const
{
   overrideIndex = _activeMapIndexOverride;
   return overrideIndex != INDEX_NONE;
}

void UTATWorldMapSubsystem::SetMapIndexOverride(int32 newIndex)
{
   // Automatically fire OnActiveMapChanged event at the end of this function if any change occured
   FActiveMapChangeTracker activeMapChangeTracker{ this };

   _activeMapIndexOverride = FMath::Clamp(newIndex, -1, _registeredMaps.Num() - 1);
}

void UTATWorldMapSubsystem::ClearMapIndexOverride()
{
   // Automatically fire OnActiveMapChanged event at the end of this function if any change occured
   FActiveMapChangeTracker activeMapChangeTracker{ this };

   _activeMapIndexOverride = INDEX_NONE;
}

void UTATWorldMapSubsystem::InitAutoSelectedMap(FVector playerLocation)
{
   // Automatically fire OnActiveMapChanged event at the end of this function if any change occured
   FActiveMapChangeTracker activeMapChangeTracker{ this };

   // Assume the map boundaries aren't overlapping (much) and just select the where the player is closest to the center.
   // Ideally we could just pick the first box that overlaps the player, but I want to make sure two slightly overlapping map boundaries
   // (eg. two floors of a building) don't cause issues.
   // Not the best heuristic but it's probably fine for now.
   float bestDistSquared = std::numeric_limits<float>::max();
   int32 bestMapIndex = INDEX_NONE;
   for (int32 i = 0; i < _registeredMaps.Num(); i++)
   {
      const FRegisteredMap& map = _registeredMaps[i];
      if (map.IsPrimary || !map.Bounds.IsInside(playerLocation))
      {
         continue;
      }

      ATATWorldMapBoundary* mapBoundaryActor =  map.BoundaryActor.Get();
      if (mapBoundaryActor == nullptr || !mapBoundaryActor->AutoSwitchToMap)
      {
         continue;
      }

      const float distSq = FVector::DistSquared(map.Bounds.GetCenter(), playerLocation);
      if (distSq < bestDistSquared)
      {
         bestDistSquared = distSq;
         bestMapIndex = i;
      }
   }

   if (_registeredMaps.IsValidIndex(bestMapIndex))
   {
      _activeMapStack.SetNum(1);
      _activeMapStack[0] = bestMapIndex;
   }
   else
   {
      _activeMapStack.Empty();
   }
}

bool UTATWorldMapSubsystem::GetWorldMapMaterialAndAnchors(TSoftObjectPtr<UTexture2D>& texture, TSoftObjectPtr<UMaterialInterface>& material, FVector2D& anchorTopLeft, FVector2D& anchorBottomRight, bool& isAutoGenerated) const
{
   texture.Reset();
   material.Reset();
   anchorTopLeft = FVector2D(0, 0);
   anchorBottomRight = FVector2D(2048, 2048);
   isAutoGenerated = false;

   if (ATATWorldMapBoundary* worldMapBoundary = _GetCurrentWorldMapBoundaryActor())
   {
      texture = worldMapBoundary->MapTexture;
      material = worldMapBoundary->GetMapMaterial();
      worldMapBoundary->GetMapTextureAnchorPoints(anchorTopLeft, anchorBottomRight);
      isAutoGenerated = worldMapBoundary->UseAutoGeneratedMap();
      return true;
   }

   return false;
}

UTexture* UTATWorldMapSubsystem::GetAutoGeneratedWorldMapTexture(bool forceUpdate)
{
   ATATWorldMapBoundary* worldMapBoundary = _GetCurrentWorldMapBoundaryActor();
   return (worldMapBoundary != nullptr)
      ? worldMapBoundary->GetAutoGeneratedMapTexture(forceUpdate)
      : nullptr;
}

bool UTATWorldMapSubsystem::GetMapInfo(FTATActiveMapInfo& mapInfo, int32 mapIndex, bool forceUpdateIfAutoGenerated)
{
   mapInfo = FTATActiveMapInfo{};

   const FRegisteredMap* registeredMap = nullptr;
   if (mapIndex == -1)
   {
      mapIndex = GetCurrentMapIndex();
   }

   if (_registeredMaps.IsValidIndex(mapIndex))
   {
      registeredMap = &_registeredMaps[mapIndex];
   }

   if (registeredMap != nullptr)
   {
      mapInfo.MapBoundary = registeredMap->BoundaryActor.Get();
      mapInfo.Label = registeredMap->Label;
      if (mapInfo.MapBoundary != nullptr)
      {
         mapInfo.Texture = mapInfo.MapBoundary->MapTexture;
         mapInfo.Material = mapInfo.MapBoundary->GetMapMaterial();
         mapInfo.MapBoundary->GetMapTextureAnchorPoints(mapInfo.AnchorTopLeft, mapInfo.AnchorBottomRight);
         mapInfo.IsAutoGenerated = mapInfo.MapBoundary->UseAutoGeneratedMap();
         if (mapInfo.IsAutoGenerated)
         {
            mapInfo.AutoGeneratedTexture = mapInfo.MapBoundary->GetAutoGeneratedMapTexture(forceUpdateIfAutoGenerated);
         }
      }
      return true;
   }

   return false;
}

void UTATWorldMapSubsystem::RegisterMapActor(UTATMapActorComponent* mapActorComponent)
{
   check(IsValid(mapActorComponent));
   check(!GetWorld()->GetGameInstance()->IsDedicatedServerInstance());

   bool alreadyInSet = false;
   _mapRepresentedActors.Add(mapActorComponent, &alreadyInSet);
   if (alreadyInSet)
   {
      UE_LOG(LogTATWorldMapSubsystem, Warning, TEXT("RegisterMapActor() called with previously-registered UTATMapActorComponent %s (owner = %s)!")
         , *mapActorComponent->GetName()
         , *mapActorComponent->GetOwner()->GetName());
      return;
   }

   OnMapActorRegistered.Broadcast(mapActorComponent);

   UE_LOG(LogTATWorldMapSubsystem, Verbose, TEXT("Registered map actor %s"), *mapActorComponent->GetOwner()->GetName());
}

void UTATWorldMapSubsystem::UnregisterMapActor(UTATMapActorComponent* mapActorComponent)
{
   check(IsValid(mapActorComponent));

   check(!GetWorld()->GetGameInstance()->IsDedicatedServerInstance());

   if (_mapRepresentedActors.Remove(mapActorComponent) > 0)
   {
      OnMapActorUnregistered.Broadcast(mapActorComponent);
      UE_LOG(LogTATWorldMapSubsystem, Verbose, TEXT("Unregistered map actor %s"), *mapActorComponent->GetOwner()->GetName());
   }
}

void UTATWorldMapSubsystem::UnregisterAllMapActorsWithSpriteTag(const FGameplayTag spriteTag)
{
   TArray<UTATMapActorComponent*> mapActorsToRemove;

   for (TWeakObjectPtr<UTATMapActorComponent> mapActor : _mapRepresentedActors)
   {
      if (mapActor.Get())
      {
         if (const FTATMapSpriteEntry* spriteEntry = mapActor->GetCurrentMapSpriteEntry())
         {
            if (spriteEntry->Tag == spriteTag)
            {
               mapActorsToRemove.Add(mapActor.Get());
            }
         }
      }
   }

   for (UTATMapActorComponent* mapActorToRemove : mapActorsToRemove)
   {
      UnregisterMapActor(mapActorToRemove);
   }
}

bool UTATWorldMapSubsystem::IsMapActorRegistered(UTATMapActorComponent* mapActorComponent) const
{
   check(IsValid(mapActorComponent));
   return _mapRepresentedActors.Contains(mapActorComponent);
}

void UTATWorldMapSubsystem::BroadcastMapActorChange(const UTATMapActorComponent* mapActorComponent)
{
   check(IsValid(mapActorComponent));
   OnMapActorChanged.Broadcast(mapActorComponent);
}

FVector2D UTATWorldMapSubsystem::ConvertWorldLocationToMapLocation(const UObject* contextObject, const FVector& worldLocation, const FTATMapRepresentationData& mapRepresentationData, const FVector2D& mapImageSize, const FVector2D& mapOffset)
{
   if (!IsValid(contextObject))
   {
      UE_LOG(LogTATWorldMapSubsystem, Error, TEXT("ConvertWorldLocationToMapLocation() | contextObject is null!"));
      return FVector2D::Zero();
   }

   UWorld* world = GEngine->GetWorldFromContextObject(contextObject, EGetWorldErrorMode::ReturnNull);
   if (world == nullptr)
   {
      UE_LOG(LogTATWorldMapSubsystem, Error, TEXT("ConvertWorldLocationToMapLocation() | world is null!"));
      return FVector2D::Zero();
   }

   UTATWorldMapSubsystem* worldMapSubsystem = world->GetSubsystem<UTATWorldMapSubsystem>();
   if (worldMapSubsystem == nullptr)
   {
      UE_LOG(LogTATWorldMapSubsystem, Error, TEXT("ConvertWorldLocationToMapLocation() | worldMapSubsystem is null!"));
      return FVector2D::Zero();
   }

   // Get map boundary actor
   const ATATWorldMapBoundary* worldMapBoundary = worldMapSubsystem->_GetCurrentWorldMapBoundaryActor();
   if (!IsValid(worldMapBoundary))
   {
      const TCHAR* extraInfo = ATATWorldSettings::Get(contextObject).WorldMapBoundary ? TEXT("") : TEXT(" (one was not defined in TATWorldSettings)");
      UE_LOG(LogTATWorldMapSubsystem, Error, TEXT("ConvertWorldLocationToMapLocation() | Unable to find any valid WorldMapBoundary actor%s! Could not return map location"), extraInfo);
      return FVector2D::Zero();
   }

   // Transform the input location to actor-space
   const FVector2D worldLocationMapActorSpace = FVector2D(worldMapBoundary->GetTransform().InverseTransformPosition(worldLocation));

   // Divide box extents (doubled, as they are half-lengths)
   const FBox mapBounds = worldMapBoundary->GetMapAreaBoundingBox();
   const FVector2D mapSize = FVector2D(mapBounds.GetSize()) / FVector2D(worldMapBoundary->GetActorScale3D());
   FVector2D normalizedLocation = worldLocationMapActorSpace / mapSize;

   // Slide from [-0.5 <-> 0.5] to [0 <-> 1]
   normalizedLocation += FVector2D(0.5, 0.5);

   // Apply map image size and offset
   FVector2D mapLocation = mapOffset + (normalizedLocation * mapImageSize);

   if (mapRepresentationData.ShowGeneralAreaOnQuestLootObtained && mapRepresentationData.IsGeneralArea)
   {
      // The radius (GeneralAreaOffset) is in slate units, so to properly scale it we need to double the mapImageSize
      // This is likely magic wishy washy math but it works...
      // We should revisit this at a later date when we change Radius from slate units to world units
      const FVector2D generalAreaOffset = (mapRepresentationData.GeneralAreaOffset / mapImageSize * 2) * mapSize;
      mapLocation += generalAreaOffset;
   }
   return mapLocation;
}

float UTATWorldMapSubsystem::ConvertMapDistanceToSlateDistance(const UObject* contextObject, float mapDistance, const FVector2D& mapDimensions)
{
   if (!IsValid(contextObject))
   {
      UE_LOG(LogTATWorldMapSubsystem, Error, TEXT("ConvertMapDistanceToSlateDistance() | contextObject is null!"));
      return 0.0f;
   }

   UWorld* world = GEngine->GetWorldFromContextObject(contextObject, EGetWorldErrorMode::ReturnNull);
   if (world == nullptr)
   {
      UE_LOG(LogTATWorldMapSubsystem, Error, TEXT("ConvertMapDistanceToSlateDistance() | world is null!"));
      return 0.0f;
   }

   UTATWorldMapSubsystem* worldMapSubsystem = world->GetSubsystem<UTATWorldMapSubsystem>();
   if (worldMapSubsystem == nullptr)
   {
      UE_LOG(LogTATWorldMapSubsystem, Error, TEXT("ConvertMapDistanceToSlateDistance() | worldMapSubsystem is null!"));
      return 0.0f;
   }

   // Get map boundary actor
   const ATATWorldMapBoundary* worldMapBoundary = worldMapSubsystem->_GetCurrentWorldMapBoundaryActor();
   if (!IsValid(worldMapBoundary))
   {
      const TCHAR* extraInfo = ATATWorldSettings::Get(contextObject).WorldMapBoundary ? TEXT("") : TEXT(" (one was not defined in TATWorldSettings)");
      UE_LOG(LogTATWorldMapSubsystem, Error, TEXT("ConvertMapDistanceToSlateDistance() | Unable to find any valid WorldMapBoundary actor%s! Could not return map location"), extraInfo);
      return 0.0f;
   }

   // This is DEFINITELY magic wishy washy math but it works...
   // We should revisit this at a later date when we change all our measurements from slate units to world units
   const FVector2D boxExtents = worldMapBoundary->GetUnscaledBoundaryExtents() * 2;
   float mapSize = mapDimensions.Length();
   float boxSize = boxExtents.Length();
   const float convertedValue = mapDistance * (mapSize / boxSize / 3);
   return convertedValue;
}

void UTATWorldMapSubsystem::RegisterMapBoundary(ATATWorldMapBoundary* mapBoundaryActor)
{
   if (mapBoundaryActor == nullptr)
   {
      return;
   }

   auto getMapLabel = [](ATATWorldMapBoundary* mapBoundary) -> FText
   {
      check(mapBoundary != nullptr);
      if (!mapBoundary->MapLabel.IsEmptyOrWhitespace())
      {
         return mapBoundary->MapLabel;
      }
#if WITH_EDITOR
      return FText::FromString(FString::Printf(TEXT("MAP LABEL MISSING: %s"), *mapBoundary->GetName()));
#else
      return FText::FromString(TEXT("MAP LABEL MISSING"));
#endif
   };

   _registeredMaps.Add(FRegisteredMap{
      .BoundaryActor = mapBoundaryActor,
      .Bounds = mapBoundaryActor->GetMapAreaBoundingBox(),
      .Label = getMapLabel(mapBoundaryActor),
      .IsPrimary = mapBoundaryActor->MapType == ETATWorldMapBoundaryType::Primary,
   });
   
   _registeredMaps.Sort([](const FRegisteredMap& a, const FRegisteredMap& b)
   {
      if (a.IsPrimary && b.IsPrimary == false) return true;
      return a.Bounds.GetCenter().Z > b.Bounds.GetCenter().Z;
   });

   for (int i = 0; i < _registeredMaps.Num(); i++)
   {
      if (_registeredMaps[i].IsPrimary)
      {
         _primaryMapIndex = i;
         break;
      }
   }
}

void UTATWorldMapSubsystem::UnregisterMapBoundary(ATATWorldMapBoundary* mapBoundaryActor)
{
}

TSoftObjectPtr<UTextureRenderTarget2D> UTATWorldMapSubsystem::GetRenderTargetForAutoGeneratedMap(ATATWorldMapBoundary* mapBoundaryActor)
{
   if (mapBoundaryActor == nullptr)
   {
      return {};
   }

   const int32 mapIndex = _FindRegisteredMapIndex(mapBoundaryActor);
   if (mapIndex == INDEX_NONE)
   {
      return {};
   }

   FRegisteredMap& thisMap = _registeredMaps[mapIndex];
   if (thisMap.IsPrimary)
   {
      return UTATProjectSettings::Get().AutoGeneratedMapRenderTarget;
   }

   const TArray<TSoftObjectPtr<UTextureRenderTarget2D>>& allSecondaryRenderTargets = UTATProjectSettings::Get().AutoGeneratedMapRenderTargets_Secondary;

   // Try and assign a render target asset to this map boundary if we don't already have one
   if (thisMap.RenderTargetIndex == INDEX_NONE)
   {
      int32 maxAssignedRenderTargetIndex = INDEX_NONE;
      for (const FRegisteredMap& map : _registeredMaps)
      {
         if (!map.IsPrimary && map.RenderTargetIndex != INDEX_NONE)
         {
            maxAssignedRenderTargetIndex = FMath::Max(maxAssignedRenderTargetIndex, map.RenderTargetIndex);
         }
      }

      const int32 nextRenderTargetIndex = maxAssignedRenderTargetIndex + 1;
      if (allSecondaryRenderTargets.IsValidIndex(nextRenderTargetIndex))
      {
         thisMap.RenderTargetIndex = nextRenderTargetIndex;
      }
   }

   return (thisMap.RenderTargetIndex != INDEX_NONE)
      ? allSecondaryRenderTargets[thisMap.RenderTargetIndex]
      : TSoftObjectPtr<UTextureRenderTarget2D>{};
}

void UTATWorldMapSubsystem::NotifyLocalPlayerInteriorMapBeginOverlap(ATATWorldMapBoundary* mapBoundary, ATATPlayerController* pc)
{
   if (!ensure(mapBoundary) || mapBoundary == _GetCurrentWorldMapBoundaryActor())
   {
      return;
   }

   // Automatically fire OnActiveMapChanged event at the end of this function if any change occured
   FActiveMapChangeTracker activeMapChangeTracker{ this };

   const int32 newMapIndex = _FindRegisteredMapIndex(mapBoundary);
   if (newMapIndex != INDEX_NONE)
   {
      _activeMapStack.Add(newMapIndex);
   }
}

void UTATWorldMapSubsystem::NotifyLocalPlayerInteriorMapEndOverlap(ATATWorldMapBoundary* mapBoundary, ATATPlayerController* pc)
{
   if (!ensure(mapBoundary))
   {
      return;
   }

   const int32 thisMapIndex = _FindRegisteredMapIndex(mapBoundary);
   if (thisMapIndex == INDEX_NONE)
   {
      UE_LOG(LogTATWorldMapSubsystem, Error, TEXT("Got EndOverlap event for unknown map boundary actor %s"), *GetNameSafe(mapBoundary));
      return;
   }

   // Automatically fire OnActiveMapChanged event at the end of this function if any change occured
   FActiveMapChangeTracker activeMapChangeTracker{ this };

   _activeMapStack.RemoveAll([thisMapIndex](int32 idx) { return idx == thisMapIndex; });
}

int32 UTATWorldMapSubsystem::_FindRegisteredMapIndex(ATATWorldMapBoundary* mapBoundary) const
{
   if (mapBoundary != nullptr)
   {
      for (int32 i = 0; i < _registeredMaps.Num(); i++)
      {
         ATATWorldMapBoundary* thisMap = _registeredMaps[i].BoundaryActor.Get();
         if (thisMap == mapBoundary)
         {
            return i;
         }
      }
   }
   return INDEX_NONE;
}

ATATWorldMapBoundary* UTATWorldMapSubsystem::_GetCurrentWorldMapBoundaryActor(int32* outIndex) const
{
   const int32 idx = GetCurrentMapIndex();
   if (_registeredMaps.IsValidIndex(idx))
   {
      if (outIndex != nullptr)
      {
         *outIndex = idx;
      }
      return _registeredMaps[idx].BoundaryActor.Get();
   }

   if (outIndex != nullptr)
   {
      *outIndex = INDEX_NONE;
   }
   return nullptr;
}

void UTATWorldMapSubsystem::_NotifyActiveMapChanged(int32 newIndex)
{
   ATATWorldMapBoundary* newMapBoundary = _registeredMaps.IsValidIndex(newIndex) ? _registeredMaps[newIndex].BoundaryActor.Get() : nullptr;
   OnActiveMapChanged.Broadcast(newIndex, newMapBoundary);
}

void UTATWorldMapSubsystem::_NotifyMapIndexOverrideChanged(int32 newIndex)
{
   ATATWorldMapBoundary* newMapBoundary = _registeredMaps.IsValidIndex(newIndex) ? _registeredMaps[newIndex].BoundaryActor.Get() : nullptr;
   OnMapIndexOverrideChanged.Broadcast(newIndex, newMapBoundary);
}

void UTATWorldMapSubsystem::_NotifyMapIndexForPlayerLocationChanged(int32 newIndex)
{
   ATATWorldMapBoundary* newMapBoundary = _registeredMaps.IsValidIndex(newIndex) ? _registeredMaps[newIndex].BoundaryActor.Get() : nullptr;
   OnMapIndexForPlayerLocationChanged.Broadcast(newIndex, newMapBoundary);
}
