// (c) 2018-2024 OtherSide Entertainment, Inc
// SPDX-License-Identifier: MIT
// Based on https://github.com/jinyuliao/GenericGraph [(c) 2016 jinyuliao, MIT License]

#pragma once

#include "CoreMinimal.h"
#include "OSEGenericGraphNode.h"
#include "OSEGenericGraphEdge.h"
#include "Engine/DataAsset.h"
#include "OSEGenericGraph.generated.h"

UENUM(BlueprintType)
enum class EOSEGenericGraphSearchMode : uint8
{
   BreadthFirstSearch = 0,
   DepthFirstSearch,
};

UCLASS(Blueprintable)
class OSEGENERICGRAPHRUNTIME_API UOSEGenericGraph : public UDataAsset
{
   GENERATED_BODY()

public:
   /// Helpers to improve readability in the Traverse callback return value
   static constexpr bool TraverseBreak = false;
   static constexpr bool TraverseContinue = true;

   UOSEGenericGraph();

#if WITH_EDITOR
   // from UObject
   virtual EDataValidationResult IsDataValid(FDataValidationContext& Context) const override;
#endif // WITH_EDITOR

   /// Node types accepted in this graph
   UPROPERTY(EditDefaultsOnly, Category = "Generic Graph")
   TArray<TSubclassOf<UOSEGenericGraphNode>> NodeTypes;

   /// Edge type accepted in this graph
   UPROPERTY(EditDefaultsOnly, Category = "Generic Graph")
   TSubclassOf<UOSEGenericGraphEdge> EdgeType;

   /// All root nodes (nodes without a parent node leading to it).
   /// This is generated by UEdGraph_GenericGraph::RebuildGenericGraph()
   UPROPERTY(BlueprintReadOnly, Category = "Generic Graph")
   TArray<UOSEGenericGraphNode*> RootNodes;

   /// All nodes in the graph.
   /// This is generated by UEdGraph_GenericGraph::RebuildGenericGraph()
   UPROPERTY(BlueprintReadOnly, Category = "Generic Graph")
   TArray<UOSEGenericGraphNode*> AllNodes;

   /// If true, transition/edge nodes of the type specified by EdgeType are created when connecting nodes.
   UPROPERTY()
   bool bEdgeTransitionEnabled = true;

   /// Iterates over the entire graph using breadth-first search or depth-first search, calling the callback for each node found.
   /// Each node will be visited exactly once.
   /// The callback should return true to continue iterating, or return false to break.
   /// You can optionally pass a starting node to search from. If not specified, it will use all root nodes.
   void TraverseNodes(EOSEGenericGraphSearchMode SearchMode, TFunctionRef<bool(UOSEGenericGraphNode*)> Callback, UOSEGenericGraphNode* StartNode = nullptr) const;

   /// Iterates over the entire graph using breadth-first search or depth-first search, calling the callback for each node and the edge it came from (if it has one).
   /// Each node will be visited exactly once for each edge that connects to it (eg. if three edges point to a node, it will be visited three times - once for each edge).
   /// The callback should return true to continue iterating, or return false to break.
   /// You can optionally pass a starting node to search from. If not specified, it will use all root nodes.
   /// NB. This function only works on graphs with transition edge nodes enabled.
   void TraverseNodeEdgePairs(EOSEGenericGraphSearchMode SearchMode, TFunctionRef<bool(UOSEGenericGraphNode*, UOSEGenericGraphEdge*)> Callback, UOSEGenericGraphNode* StartNode = nullptr) const;

   /// Iterates over all nodes backwards, starting from a base node.
   /// This essentially gives you all parent nodes of a node.
   void TraverseNodesBackward(EOSEGenericGraphSearchMode SearchMode, UOSEGenericGraphNode* BaseNode, TFunctionRef<bool(UOSEGenericGraphNode*)> Callback, bool VisitBaseNode = false) const;

   using FCycleDetectedCallback = TFunctionRef<void(TArrayView<UOSEGenericGraphNode*>)>;

   /// Checks if the graph has any cycles, returning the number of cycles found
   int32 FindCycles(FCycleDetectedCallback CycleDetectedCallback) const;

private:
   struct FCycleCheckerState;
   static void FindCyclesInternal(UOSEGenericGraphNode* Node, FCycleDetectedCallback CycleDetectedCallback, FCycleCheckerState& State);

#ifdef WITH_EDITOR
   bool _CheckForDuplicateNodes() const;
#endif

public:

   UFUNCTION(BlueprintCallable, BlueprintPure = false, Category = "Generic Graph")
   FString ToDebugString() const;

   /// Removes all nodes from the graph
   void ClearGraph();

   /// Finds a graph node by it's unique ID
   UFUNCTION(BlueprintPure, Category = "Generic Graph")
   UOSEGenericGraphNode* GetNodeByGuid(const FGuid& Guid) const;

   void RebuildNodeIdMap();

#if WITH_EDITOR
   /// Returns the name of the type of this graph. This is the text that appears in the bottom-right of the graph editor.
   virtual FText GetGraphTypeDisplayName() const;
#endif

   UPROPERTY(Transient)
   TMap<FGuid, UOSEGenericGraphNode*> NodeIdMap;

#if WITH_EDITORONLY_DATA
   UPROPERTY()
   TObjectPtr<class UEdGraph> EdGraph = nullptr;

   /// Allow clicking a node or pressing F2 while the node is selected in the editor to show a text entry widget.
   /// Requires that the node type's IsTitleEditable() method returns true.
   UPROPERTY()
   bool bCanRenameNode = true;

   /// Allow nodes to connect back on themselves. If disabled, connections are checked while creating them to ensure no cycles can be created in the editor.
   /// Asset validation also verifies this is the case.
   UPROPERTY()
   bool bCanBeCyclical = false;
#endif
};
