// (c) 2018-2025 OtherSide Entertainment, Inc
// SPDX-License-Identifier: MIT

#include "Environment/TATSplineUtilities.h"

// tat
#include "Graphics/TATHighlightStateMgrComponent.h"

// ue
#include "Components/SplineComponent.h"
#include "Components/SplineMeshComponent.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(TATSplineUtilities)

DEFINE_LOG_CATEGORY_STATIC(LogTATSplineUtilities, Log, All);

// We'll add this tag to all auto-generated spline mesh components so we know what to destroy when recreating them.
static const FName kTempSplineMeshComponentTag = FName("AutoGeneratedSplineMeshComponent");

static const FTATSplineMeshSegment kDefaultSplineMeshSegment = FTATSplineMeshSegment{};

namespace SplineHelpers
{
   struct FSplineMeshUpdateState
   {
      USplineComponent* Spline;
      const FTATSplineMeshConfig& Config;
      int32 NumFlexSegments = 0;
      float AvailableFlexLength = 0;
      TArray<int32, TInlineAllocator<48>> VisibleSegmentIndices;
      int32 NumStaticMeshAssets = 0;

      FSplineMeshUpdateState(USplineComponent* spline, const FTATSplineMeshConfig& config)
         : Spline(spline)
         , Config(config)
      {
         check(Spline != nullptr);
         const float totalSplineLength = Spline->GetSplineLength();
         AvailableFlexLength = totalSplineLength;

         if (Config.Mesh != nullptr)
         {
            ++NumStaticMeshAssets;
         }

         if (Config.Segments.IsEmpty())
         {
            return;
         }

         // Determine how much "excess" space we have for auto-length segments
         for (const FTATSplineMeshSegment& segment : Config.Segments)
         {
            // Keep track of how many mesh assets we have
            if (segment.Mesh != nullptr)
            {
               ++NumStaticMeshAssets;
            }

            if (segment.LengthMode == ETATSplineSegmentLengthMode::Auto)
            {
               ++NumFlexSegments;
            }
            else
            {
               AvailableFlexLength -= segment.GetSegmentLength(totalSplineLength, 0.0f);
            }
         }

         const float autoSegmentLength = (NumFlexSegments > 0) ? (AvailableFlexLength / static_cast<float>(NumFlexSegments)) : 0.0f;

         // Figure out which segments are actually visible based on the available space
         float lastSegmentEndDist = 0;
         for (int32 i = 0; i < NumSegments(); i++)
         {
            const FTATSplineMeshSegment& segment = GetSplineMeshSegmentConfig(i);
            float segmentLength = segment.GetSegmentLength(totalSplineLength, autoSegmentLength);
            const bool atEndOfSpline = lastSegmentEndDist + segmentLength >= totalSplineLength;
            if (atEndOfSpline)
            {
               // Clamp this segment's length to the remaining space on the spline.
               // If there's not enough space for even that (eg. the last segment brought us to the exact length), we're done.
               segmentLength = totalSplineLength - lastSegmentEndDist;
               if (segmentLength <= 0)
               {
                  break;
               }
            }

            // Mark this segment as visible
            VisibleSegmentIndices.Add(i);

            if (atEndOfSpline)
            {
               break;
            }

            lastSegmentEndDist += segmentLength;
         }
      }

      int32 NumSegments() const
      {
         return FMath::Max(1, Config.Segments.Num());
      }

      int32 NumVisibleSegments() const
      {
         return VisibleSegmentIndices.Num();
      }

      const FTATSplineMeshSegment& GetSplineMeshSegmentConfig(int32 idx) const
      {
         return Config.Segments.IsValidIndex(idx) ? Config.Segments[idx] : kDefaultSplineMeshSegment;
      }

      // Callback example: [](const FTATSplineMeshSegment& segment, UStaticMesh* staticMesh, float segmentStartDist, float segmentLength, const FTATSplineMeshSegment* nextVisibleSegment) {}
      template<typename Lambda>
      void ForEachVisibleSplineMeshSegment(Lambda&& callback) const
      {
         // If we don't have any valid static mesh assets, then we have no visible segments.
         if (NumStaticMeshAssets == 0)
         {
            return;
         }

         const float splineLength = Spline->GetSplineLength();

         if (Config.Segments.IsEmpty())
         {
            // If we have no segments but NumStaticMeshAssets is greater than zero, then Config.Mesh must be valid
            check(Config.Mesh != nullptr);

            // Auto-generate segments based on spline points
            const int32 numSplinePoints = Spline->GetNumberOfSplinePoints();
            FTATSplineMeshSegment nextSegment = kDefaultSplineMeshSegment;
            for (int32 splineEndIndex = 1; splineEndIndex < numSplinePoints; splineEndIndex++)
            {
               const int32 splineStartIndex = splineEndIndex - 1;
               const float segmentStartDistance = Spline->GetDistanceAlongSplineAtSplinePoint(splineStartIndex);
               const float segmentEndDistance = Spline->GetDistanceAlongSplineAtSplinePoint(splineEndIndex);
               const float segmentLength = segmentEndDistance - segmentStartDistance;
               // We pass a pointer to the "next" segment only if there IS a next segment.
               const FTATSplineMeshSegment* nextSegmentPtr = (splineEndIndex < numSplinePoints - 1) ? &nextSegment : nullptr;
               if (segmentLength > 0)
               {
                  callback(kDefaultSplineMeshSegment, Config.Mesh, segmentStartDistance, segmentLength, nextSegmentPtr);
               }
            }
            return;
         }

         const float autoSegmentLength = (NumFlexSegments > 0) ? (AvailableFlexLength / static_cast<float>(NumFlexSegments)) : 0.0f;

         float lastSegmentEndDist = 0;
         for (int32 i = 0; i < VisibleSegmentIndices.Num(); i++)
         {
            const int32 segmentIdx = VisibleSegmentIndices[i];
            check(Config.Segments.IsValidIndex(segmentIdx));
            const FTATSplineMeshSegment& segment = Config.Segments[segmentIdx];

            const FTATSplineMeshSegment* nextSegment = nullptr;
            if (VisibleSegmentIndices.IsValidIndex(i + 1))
            {
               const int32 nextVisibleSegmentIdx = VisibleSegmentIndices[i + 1];
               check(Config.Segments.IsValidIndex(nextVisibleSegmentIdx));
               nextSegment = &Config.Segments[nextVisibleSegmentIdx];
            }

            const float segmentLength = segment.GetSegmentLength(splineLength, autoSegmentLength);
            ensure(segmentLength > 0);
            if (UStaticMesh* staticMeshAsset = (segment.Mesh != nullptr) ? segment.Mesh : Config.Mesh)
            {
               callback(segment, staticMeshAsset, lastSegmentEndDist, segmentLength, nextSegment);
            }
            lastSegmentEndDist += segmentLength;
         }
      }
   };

   template<typename ComponentType, typename Lambda>
   FORCEINLINE void ForEachComponentWithTag(AActor* actor, FName componentTag, Lambda&& callback)
   {
      check(actor != nullptr);
      for (UActorComponent* actorComponent : actor->GetComponents())
      {
         ComponentType* comp = Cast<ComponentType>(actorComponent);
         if (comp != nullptr && comp->ComponentHasTag(componentTag))
         {
            callback(comp);
         }
      }
   }
} // namespace SplineHelpers

// static
void UTATSplineUtilities::AutoGenerateSplineMeshComponents(USplineComponent* splineComponent, const FTATSplineMeshConfig& splineMeshConfig)
{
   if (splineComponent == nullptr)
   {
      return;
   }

   AActor* actor = splineComponent->GetOwner();
   if (actor == nullptr)
   {
      return;
   }

   SplineHelpers::FSplineMeshUpdateState splineState{ splineComponent, splineMeshConfig };

   // Calculate the total required number of spline mesh components we'll need.
   // This is basically just the number of spline segments, but each segment can subdivide into multiple meshes.
   int32 numRequiredSplineMeshComponents = 0;
   splineState.ForEachVisibleSplineMeshSegment(
      [&numRequiredSplineMeshComponents](const FTATSplineMeshSegment& segment, UStaticMesh* staticMeshAsset, float segmentStartDist, float segmentLength, const FTATSplineMeshSegment* nextVisibleSegment)
      {
         numRequiredSplineMeshComponents += segment.GetNumSegments();
      });

   // Next, find any existing components
   TArray<USplineMeshComponent*, TInlineAllocator<48>> existingSplineMeshComponents;
   SplineHelpers::ForEachComponentWithTag<USplineMeshComponent>(actor, kTempSplineMeshComponentTag,
      [&existingSplineMeshComponents](USplineMeshComponent* comp)
      {
         existingSplineMeshComponents.Add(comp);
      });

   int32 numDestroyedSplineMeshComponents = 0;

   // If we have more components than we need, destroy the extra
   if (existingSplineMeshComponents.Num() > numRequiredSplineMeshComponents)
   {
      while (existingSplineMeshComponents.Num() > numRequiredSplineMeshComponents)
      {
         USplineMeshComponent* comp = existingSplineMeshComponents.Pop();
         check(comp != nullptr);
         actor->RemoveInstanceComponent(comp);
         comp->DestroyComponent();
         ++numDestroyedSplineMeshComponents;
      }

      // clear out the old segments and force GC to prevent memory leaks
      GEngine->ForceGarbageCollection(true);
   }

   UE_LOG(LogTATSplineUtilities, Verbose, TEXT("Destroyed %i extra spline mesh components, need %i, have %i existing"), numDestroyedSplineMeshComponents, numRequiredSplineMeshComponents, existingSplineMeshComponents.Num());

   int32 _splineMeshComponentIndex = 0; // only used internally in getOrCreateSplineMeshComponent
   auto getOrCreateSplineMeshComponent = [&](bool& outIsNewComponent) -> USplineMeshComponent*
   {
      const int32 idx = _splineMeshComponentIndex;
      ++_splineMeshComponentIndex;
      outIsNewComponent = !existingSplineMeshComponents.IsValidIndex(idx);
      if (outIsNewComponent)
      {
         UE_LOG(LogTATSplineUtilities, VeryVerbose, TEXT("Spawning new spline mesh component"));
         USplineMeshComponent* splineMeshComponent = NewObject<USplineMeshComponent>(actor);
         check(splineMeshComponent != nullptr);

         // This will set the component's CreationMethod to "Instanced", which causes it to show up in the level editor when the actor is selected
         actor->AddInstanceComponent(splineMeshComponent);

         splineMeshComponent->SetNetAddressable();
         return splineMeshComponent;
      }
      return existingSplineMeshComponents[idx];
   };

   // This should be called on the component spawned by getOrCreateSplineMeshComponent if it returned a new component
   auto finishSpawningNewSplineMeshComponent = [actor, splineComponent, &splineMeshConfig](USplineMeshComponent* splineMeshComponent)
   {
      check(splineMeshComponent != nullptr);
      splineMeshComponent->ComponentTags.Add(kTempSplineMeshComponentTag);
      splineMeshComponent->SetMobility(splineMeshConfig.SegmentMobility);
      constexpr bool manualAttachment = true;
      actor->FinishAddComponent(splineMeshComponent, manualAttachment, FTransform::Identity);
      splineMeshComponent->AttachToComponent(splineComponent, FAttachmentTransformRules::KeepRelativeTransform);
   };

   // If we have no defined segments (just a default mesh, presumably), automatically compute the number of subdivisions based on the number of spline points
   const bool useAutoSubdivCount = splineMeshConfig.Segments.Num() == 0;
   const int32 autoSubdivCount = splineComponent->GetNumberOfSplineSegments();

   splineState.ForEachVisibleSplineMeshSegment([&](const FTATSplineMeshSegment& segment, UStaticMesh* staticMeshAsset, float segmentStartDist, float segmentLength, const FTATSplineMeshSegment* nextVisibleSegment)
   {
      check(segmentLength > 0);
      check(staticMeshAsset != nullptr);

      // Use the spline mesh axis in the segment if it has an explicitly assigned mesh, otherwise use the one defined in the base config.
      const ESplineMeshAxis::Type meshAxis = (segment.Mesh != nullptr) ? segment.SplineMeshAxis : splineState.Config.SplineMeshAxis;

      const float subdivLength = segmentLength / segment.GetNumSegments();

      float endRoll;
      FVector2D endScale;
      if (nextVisibleSegment != nullptr)
      {
         endRoll = segment.UseEndRoll ? segment.EndRoll : nextVisibleSegment->StartRoll;
         endScale = segment.UseEndScale ? segment.EndScale : nextVisibleSegment->StartScale;
      }
      else
      {
         // This is the last segment so there isn't a next one
         endRoll = segment.UseEndRoll ? segment.EndRoll : 0.0f;
         endScale = segment.UseEndScale ? segment.EndScale : FVector2D::One();
      }

      for (int32 subdivIdx = 0; subdivIdx < segment.GetNumSegments(); subdivIdx++)
      {
         // set up the spline mesh for this segment
         bool isNewComponent = false;
         USplineMeshComponent* comp = getOrCreateSplineMeshComponent(isNewComponent);
         if (!ensureMsgf(comp, TEXT("Failed to spawn spline mesh component")))
         {
            return;
         }

         comp->SetStaticMesh(staticMeshAsset);
         comp->SetForwardAxis(meshAxis);
         comp->SetCollisionEnabled(splineMeshConfig.SegmentCollision);
         comp->SetCollisionProfileName(splineMeshConfig.SegmentCollisionProfile.Name);
         comp->SetWorldTransform(splineComponent->GetComponentTransform());

         // Update start and end positions
         const float subdivStartLength = segmentStartDist + (subdivIdx * subdivLength);
         const float subdivEndLength = segmentStartDist + ((subdivIdx + 1) * subdivLength);

         comp->SplineParams.StartPos = splineComponent->GetLocationAtDistanceAlongSpline(subdivStartLength, ESplineCoordinateSpace::Local);
         comp->SplineParams.EndPos = splineComponent->GetLocationAtDistanceAlongSpline(subdivEndLength, ESplineCoordinateSpace::Local);

         const float tangentScale = segment.UseTangentScale ? segment.TangentScale : (1.0f / static_cast<float>(segment.GetNumSegments()));
         comp->SplineParams.StartTangent = splineComponent->GetTangentAtDistanceAlongSpline(subdivStartLength, ESplineCoordinateSpace::Local) * tangentScale;
         comp->SplineParams.EndTangent = splineComponent->GetTangentAtDistanceAlongSpline(subdivEndLength, ESplineCoordinateSpace::Local) * tangentScale;

         // for multiple subdivisions in one segment, lerp between the beginning and end of the segment
         const float startLerpAlpha = (subdivIdx * subdivLength) / segmentLength;
         const float endLerpAlpha = ((subdivIdx + 1) * subdivLength) / segmentLength;

         // Compute the segment's roll
         comp->SplineParams.StartRoll = FMath::DegreesToRadians(FMath::Lerp(segment.StartRoll, endRoll, startLerpAlpha));
         comp->SplineParams.EndRoll = FMath::DegreesToRadians(FMath::Lerp(segment.StartRoll, endRoll, endLerpAlpha));

         // Compute the segment's scale
         comp->SplineParams.StartScale = FMath::Lerp(segment.StartScale, endScale, startLerpAlpha);
         comp->SplineParams.EndScale = FMath::Lerp(segment.StartScale, endScale, endLerpAlpha);

         // finish creating and registering the component
         if (isNewComponent)
         {
            finishSpawningNewSplineMeshComponent(comp);
         }

         // make sure the spline data updates correctly
         comp->bMeshDirty = true;
         comp->UpdateRenderStateAndCollision();
      }
   });
}

// static
void UTATSplineUtilities::ForEachAutoGeneratedSplineMeshComponent(USplineComponent* splineComponent, TFunctionRef<void(USplineMeshComponent*)> callback)
{
   AActor* actor = (splineComponent != nullptr) ? splineComponent->GetOwner() : nullptr;
   if (actor == nullptr)
   {
      return;
   }

   SplineHelpers::ForEachComponentWithTag<USplineMeshComponent>(actor, kTempSplineMeshComponentTag,
      [callback](USplineMeshComponent* comp)
      {
         callback(comp);
      });
}

// static
void UTATSplineUtilities::GetAllAutoGeneratedSplineMeshComponents(USplineComponent* splineComponent, TArray<USplineMeshComponent*>& splineMeshComponents)
{
   splineMeshComponents.Reset();
   if (AActor* actor = (splineComponent != nullptr) ? splineComponent->GetOwner() : nullptr)
   {
      SplineHelpers::ForEachComponentWithTag<USplineMeshComponent>(actor, kTempSplineMeshComponentTag,
         [&](USplineMeshComponent* comp)
         {
            splineMeshComponents.Add(comp);
         });
   }
}

// static
void UTATSplineUtilities::HighlightAllAutoGeneratedSplineMeshComponents(USplineComponent* splineComponent, bool isHighlighted)
{
   AActor* actor = (splineComponent != nullptr) ? splineComponent->GetOwner() : nullptr;
   if (actor == nullptr)
   {
      return;
   }

   UTATHighlightStateMgrComponent::HighlightMeshesWithTag(actor, kTempSplineMeshComponentTag, isHighlighted);
}

// static
void UTATSplineUtilities::SetMaterialOnAllAutoGeneratedSplineMeshComponents(USplineComponent* splineComponent, int32 materialIndex, UMaterialInterface* material)
{
   if (AActor* actor = (splineComponent != nullptr) ? splineComponent->GetOwner() : nullptr)
   {
      SplineHelpers::ForEachComponentWithTag<USplineMeshComponent>(actor, kTempSplineMeshComponentTag,
         [&](USplineMeshComponent* comp)
         {
            comp->SetMaterial(materialIndex, material);
         });
   }
}

// static
int32 UTATSplineUtilities::DestroyAllAutoGeneratedSplineMeshComponents(USplineComponent* splineComponent)
{
   if (AActor* actor = (splineComponent != nullptr) ? splineComponent->GetOwner() : nullptr)
   {
      // Collect the components first, then destroy them. This avoids mutating the actor's component set while iterating over it.
      TArray<USplineMeshComponent*, TInlineAllocator<48>> splineMeshComponents;
      SplineHelpers::ForEachComponentWithTag<USplineMeshComponent>(actor, kTempSplineMeshComponentTag,
         [&](USplineMeshComponent* comp)
         {
            splineMeshComponents.Add(comp);
         });
      for (USplineMeshComponent* comp : splineMeshComponents)
      {
         comp->DestroyComponent();
      }
      return splineMeshComponents.Num();
   }
   return 0;
}

namespace SplineHelpers
{
   /// Sets the number of points on a spline component.
   /// Maintains the existing start and end locations when possible by adding or removing points from the middle.
   void SetNumSplinePointsMiddleOut(USplineComponent* comp, int32 targetNumPoints)
   {
      check(comp != nullptr);
      static constexpr bool updateSpline = false;
      const int32 initialNumPoints = comp->GetNumberOfSplinePoints();
      if (initialNumPoints == targetNumPoints)
      {
         return;
      }

      if (targetNumPoints <= 0)
      {
         comp->ClearSplinePoints(updateSpline);
      }
      else if (initialNumPoints <= 0)
      {
         // starting with an empty spline so there's no existing data to attempt to preserve
         for (int32 i = 0; i < targetNumPoints; i++)
         {
            comp->AddSplinePoint(FVector(static_cast<float>(i * 100), 0, 0), ESplineCoordinateSpace::Local, updateSpline);
         }
      }
      else if (initialNumPoints == 1 && targetNumPoints > 1)
      {
         // starting with exactly one point, just append some extra points to the end
         const FVector baseLocalPoint = comp->GetSplinePointAt(0, ESplineCoordinateSpace::Local).Position;
         for (int32 i = 0; i < targetNumPoints - initialNumPoints; i++)
         {
            comp->AddSplinePoint(baseLocalPoint + FVector(static_cast<float>((i + 1) * 100), 0, 0), ESplineCoordinateSpace::Local, updateSpline);
         }
      }
      else if (initialNumPoints > targetNumPoints)
      {
         // Remove points from the middle of the spline only in an attempt to preserve the endpoint locations and tangents
         while (comp->GetNumberOfSplinePoints() > targetNumPoints)
         {
            const int32 numCurrentPoints = comp->GetNumberOfSplinePoints();
            static constexpr int32 firstIndex = 0;
            const int32 lastIndex = numCurrentPoints - 1;
            // Remove a "middle" index
            comp->RemoveSplinePoint(FMath::Clamp(numCurrentPoints / 2, firstIndex + 1, lastIndex - 1), updateSpline);
         }
      }
      else if (initialNumPoints < targetNumPoints)
      {
         ensure(initialNumPoints >= 2);

         // Add points in the middle of the spline
         const int32 numNewPoints = targetNumPoints - initialNumPoints;

         // Find the biggest spline segment to add points to
         int32 segmentStartIndex = INDEX_NONE;
         FFloatInterval segmentDistInterval{};
         float bestSegmentLength = -9999999.0f;
         for (int32 i = 1; i < initialNumPoints; i++)
         {
            const int32 prevIndex = i - 1;
            const float distA = comp->GetDistanceAlongSplineAtSplinePoint(prevIndex);
            const float distB = comp->GetDistanceAlongSplineAtSplinePoint(i);
            const float segmentLength = FMath::Max(0.0f, distB - distA);
            if (segmentLength > bestSegmentLength)
            {
               segmentStartIndex = prevIndex;
               segmentDistInterval = { distA, distB };
               bestSegmentLength = segmentLength;
            }
         }

         if (!ensure(bestSegmentLength > 0.0f))
         {
            return;
         }

         // Precompute new interpolated spline point positions so the spline doesn't change while we're finding them
         TArray<FVector, TInlineAllocator<8>> newSplinePointPositions;
         newSplinePointPositions.SetNumZeroed(numNewPoints);
         for (int32 i = 0; i < numNewPoints; i++)
         {
            const float alpha = static_cast<float>(i + 1) / static_cast<float>(numNewPoints + 1);
            const float interpolatedDist = FMath::Lerp(segmentDistInterval.Min, segmentDistInterval.Max, alpha);
            newSplinePointPositions[i] = comp->GetLocationAtDistanceAlongSpline(interpolatedDist, ESplineCoordinateSpace::Local);
         }

         // Add the new spline points
         int32 nextIndexToInsertAfter = segmentStartIndex;
         check(nextIndexToInsertAfter != INDEX_NONE);
         for (int32 i = 0; i < numNewPoints; i++)
         {
            comp->AddSplinePointAtIndex(newSplinePointPositions[i], nextIndexToInsertAfter, ESplineCoordinateSpace::Local, updateSpline);
            ++nextIndexToInsertAfter;
         }
      }
   }
}

// static
void UTATSplineUtilities::MakeCableFromStartAndEnd(FVector start, FVector end, TArray<FTATCablePoint>& cablePoints, float cableTension,
   float cableMassPerMeter, int32 numCenterPoints, bool fixedStartPoint, bool fixedEndPoint)
{
   const int32 numPoints = 2 + FMath::Max(0, numCenterPoints);
   cablePoints.SetNumZeroed(numPoints);

   const float cableLength = FMath::Max(0.01f, FVector::Distance(start, end));
   const int32 numPointsWithMass = FMath::Max(1, numCenterPoints + (fixedStartPoint ? 0 : 1) + (fixedEndPoint ? 0 : 1));
   const float massPerCablePoint = (cableLength * 0.01f * FMath::Max(0.001f, cableMassPerMeter)) / static_cast<float>(numPointsWithMass);
   const float baseSegmentRestLength = cableLength / static_cast<float>(numPoints - 1);
   const float segmentRestLength = FMath::Max(0.01f, baseSegmentRestLength * (1.0f / FMath::Max(0.001f, cableTension)));

   cablePoints[0] = FTATCablePoint(start, fixedStartPoint ? 0.0f : massPerCablePoint, segmentRestLength);
   cablePoints.Last() = FTATCablePoint(end, fixedEndPoint ? 0.0f : massPerCablePoint, segmentRestLength);
   for (int32 i = 1; i < numPoints - 1; i++)
   {
      const float alpha = static_cast<float>(i + 1) / static_cast<float>(numPoints + 1);
      cablePoints[i] = FTATCablePoint(FMath::Lerp(start, end, alpha), massPerCablePoint, segmentRestLength);
   }
}

// static
void UTATSplineUtilities::RunCableSimulationTimestep(const FTATCableSimulationSettings& settings, TArray<FTATCablePoint>& cablePoints, float deltaSeconds)
{
   deltaSeconds = FMath::Max(deltaSeconds, 0.0001f);

   // Reset acceleration for all points
   for (FTATCablePoint& pt : cablePoints)
   {
      pt.Acceleration = pt.IsSimulated() ? FVector(0.0f, 0.0f, -settings.Gravity) : FVector::ZeroVector;
   }

   // Compute acceleration based on spring forces between adjacent points for each cable segment
   for (int32 i = 1; i < cablePoints.Num(); i++)
   {
      FTATCablePoint& pt0 = cablePoints[i - 1];
      FTATCablePoint& pt1 = cablePoints[i];
      if (!pt0.IsSimulated() && !pt1.IsSimulated())
      {
         continue;
      }

      // Calculate the spring force
      const FVector segmentDelta = pt1.Position - pt0.Position;
      const float forceMagnitude = settings.SpringConstant * (segmentDelta.Length() - pt0.SegmentRestLength);

      // Apply force (relative to mass) equally to the acceleration of both points
      const FVector force = forceMagnitude * segmentDelta.GetSafeNormal();
      if (pt0.IsSimulated())
      {
         pt0.Acceleration += force / pt0.Mass;
      }
      if (pt1.IsSimulated())
      {
         pt1.Acceleration -= force / pt1.Mass;
      }
   }

   // Update positions and velocities using verlet integration
   for (FTATCablePoint& pt : cablePoints)
   {
      if (!pt.IsSimulated())
      {
         continue;
      }
      const FVector newPosition = pt.Position + pt.Velocity * deltaSeconds + 0.5f * pt.Acceleration * FMath::Square(deltaSeconds);
      const FVector newVelocity = (newPosition - pt.Position) / deltaSeconds;
      pt.Velocity = newVelocity * settings.Damping;
      pt.Position = newPosition;
   }
}

// static
void UTATSplineUtilities::ApplyCablePointsToSplineComponent(USplineComponent* splineComponent, const TArray<FTATCablePoint>& cablePoints,
   TEnumAsByte<ESplineCoordinateSpace::Type> coordSpace, bool updateSpline)
{
   if (splineComponent == nullptr)
   {
      return;
   }

   if (splineComponent->GetNumberOfSplinePoints() != cablePoints.Num())
   {
      SplineHelpers::SetNumSplinePointsMiddleOut(splineComponent, cablePoints.Num());
   }

   static constexpr bool intermediateUpdateSpline = false;
   for (int32 i = 0; i < cablePoints.Num(); i++)
   {
      // Reset spline point type for this spline point
      if (i > 0 && i < cablePoints.Num() - 1)
      {
         splineComponent->SetSplinePointType(i, ESplinePointType::Curve, intermediateUpdateSpline);
      }

      splineComponent->SetLocationAtSplinePoint(i, cablePoints[i].Position, coordSpace, intermediateUpdateSpline);
   }

   if (updateSpline)
   {
      splineComponent->UpdateSpline();
   }
}

// static
void UTATSplineUtilities::SetupSplineComponentWithCableSimulation(USplineComponent* splineComponent, FVector start, FVector end, const FTATCableSimulationSettings& settings,
      TArray<FTATCablePoint>& cablePoints, TEnumAsByte<ESplineCoordinateSpace::Type> coordSpace, float cableTension, float cableMassPerMeter, int32 numCenterPoints,
      bool fixedStartPoint, bool fixedEndPoint, float simulationTimeSeconds, int32 simulationStepsPerSecond, bool updateSpline)
{
   if (splineComponent == nullptr || FVector::DistSquared(start, end) <= FMath::Square(0.01f) || simulationTimeSeconds <= 0 || simulationStepsPerSecond <= 0)
   {
      return;
   }

   MakeCableFromStartAndEnd(start, end, cablePoints, cableTension, cableMassPerMeter, numCenterPoints, fixedStartPoint, fixedEndPoint);

   // Nothing to simulate if we have no center points
   if (numCenterPoints <= 0)
   {
      return;
   }

   simulationTimeSeconds = FMath::Max(0.0f, simulationTimeSeconds);
   simulationStepsPerSecond = FMath::Max(1, simulationStepsPerSecond);
   const float simulationDeltaSeconds = 1.0f / static_cast<float>(simulationStepsPerSecond);
   const int32 numSimulationSteps = FMath::Max(1, FMath::RoundToInt32(simulationTimeSeconds * static_cast<float>(simulationStepsPerSecond)));
   for (int32 i = 0; i < numSimulationSteps; i++)
   {
      RunCableSimulationTimestep(settings, cablePoints, simulationDeltaSeconds);
   }

   ApplyCablePointsToSplineComponent(splineComponent, cablePoints, coordSpace, updateSpline);
}
