// (c) 2018-2024 OtherSide Entertainment, Inc
// SPDX-License-Identifier: MIT

#pragma once

// tat
#include "Loot/TATLootTypes.h"
#include "UI/TATFilteredListViewWrapperWidget.h"

// ue
#include "GameplayTagContainer.h"
#include "UObject/WeakObjectPtrTemplates.h"

#include "TATLootInventoryListWidget.generated.h"

class UListView;
class UTATSavedLootItemUIProxy;
class UTATLootInventoryListEntryWidget;

UCLASS()
class TAT_API UTATLootInventoryListWidget : public UTATFilteredListViewWrapperWidget
{
   GENERATED_BODY()

public:
   // from UTATFilteredListViewWrapperWidget
   virtual void SetEntries(const TArray<UObject*>& entryObjects) override;

   UFUNCTION(BlueprintCallable)
   void ClearSelection();

   DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnSelectionChangedEvent, const TSet<UTATSavedLootItemUIProxy*>&, SelectedEntries);
   UPROPERTY(BlueprintAssignable)
   FOnSelectionChangedEvent OnSelectionChanged;

protected:
   // from UUserWidget
   virtual void NativeOnInitialized() override;
   virtual FReply NativeOnFocusReceived(const FGeometry& inGeometry, const FFocusEvent& inFocusEvent) override;

   // from UTATFilteredListViewWrapperWidget
   virtual void OnEntriesUpdated(TArray<UObject*>& entries) override;
   virtual void OnFiltersChanged_Implementation() override;

   // Checked and assumed valid (i.e. widget has been generated)
   UFUNCTION(BlueprintCallable)
   UTATLootInventoryListEntryWidget* GetWidgetForItem(const UObject* item) const;

   UFUNCTION(BlueprintCallable)
   FORCEINLINE void FilterByMajorLoot(TArray<UObject*>& itemsToFilter) { _FilterByLootType(ETATLootType::MajorLoot, itemsToFilter); }

   UFUNCTION(BlueprintCallable)
   FORCEINLINE void FilterByMinorLoot(TArray<UObject*>& itemsToFilter) { _FilterByLootType(ETATLootType::MinorLoot, itemsToFilter); }

private:
   // Unlike GetWidgetForItem, this method is unchecked but instead validates that the the widget has finished being generated by the UListView
   UTATLootInventoryListEntryWidget* _GetWidgetForItemIfGenerated(const UObject* item) const;

   void _ValidateSelectedEntries();

   void _FilterByLootType(ETATLootType lootType, TArray<UObject*>& itemsToFilter);

   void _OnWidgetGeneratedForItem(UUserWidget& widget);
   void _OnWidgetReleasedForItem(UUserWidget& widget);

   void _OnEntryFocusStateChanged(UTATSavedLootItemUIProxy* item, bool hasFocus);
   void _OnEntryInteracted(UTATSavedLootItemUIProxy* item);

   // The item/widget combo from which the user navigates the list
   friend struct FSelector;
   struct FSelector
   {
   public:
      void Initialize(UTATLootInventoryListWidget* listWidget);

      void OnListViewEntriesChanged();

      void TryGrabFocus();

      FORCEINLINE UTATSavedLootItemUIProxy* GetItem() const { return _entryItem.Get(); }

      void SetItem(UTATSavedLootItemUIProxy* item);
      void SetWidget(UTATLootInventoryListEntryWidget* widget);

   private:
      // Tries to make sure that _entryItem is non-null
      void _TryEnforceValidItem();

      // Makes sure that _entryItem is in the list widget's selected entries list
      // Useful in single-select modes to enforce that some item is selected for viewing/modifying
      void _EnsureItemIsSelected();

      TWeakObjectPtr<UTATLootInventoryListWidget> _listWidget = nullptr;
      TWeakObjectPtr<UTATSavedLootItemUIProxy> _entryItem = nullptr;
      TWeakObjectPtr<UTATLootInventoryListEntryWidget> _entryWidget = nullptr;
   };
   FSelector _selector;

   UPROPERTY()
   TSet<UTATSavedLootItemUIProxy*> _selectedEntries;

};
