;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
ManifestDependencies=../Engine/Content/Localization/Editor/Editor.manifest
SourcePath=Content/Localization/Game
DestinationPath=Content/Localization/Game
ManifestName=Game.manifest
ArchiveName=Game.archive
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=it-IT
CulturesToGenerate=de-DE
CulturesToGenerate=es-ES
CulturesToGenerate=pt-BR
CulturesToGenerate=zh-Hans
CulturesToGenerate=ja-JP
CulturesToGenerate=zh-Hant
CulturesToGenerate=fr-FR

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=%LOCPROJECTROOT%*
SearchDirectoryPaths=%LOCENGINEROOT%Source/Runtime/Engine/Private
ExcludePathFilters=Config/Localization/*
ExcludePathFilters=Plugins/OSEAI/Source/OSEAI/Private/AI/EnvironmentQuery/Tests/*
ExcludePathFilters=Plugins/OSEGenericGraph/*
ExcludePathFilters=Plugins/ThirdParty/BlueprintAssist/*
ExcludePathFilters=Plugins/ThirdParty/GameAnalytics/Source/GameAnalyticsEditor/*
ExcludePathFilters=Plugins/Wwise/Wwise/Source/AudiokineticTools/*
ExcludePathFilters=Plugins/Wwise/Wwise/Source/WwiseProjectDatabase/*
ExcludePathFilters=Plugins/Wwise/Wwise/Source/WwiseReconcile/*
ExcludePathFilters=Source/TATEditor/*
ExcludePathFilters=Saved/Diff/*
ExcludePathFilters=Saved/Temp/*
ExcludePathFilters=Plugins/OSECore/Source/OSECoreEditor/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/ActorEditorContext/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/ActorPartition/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/AI/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Analytics/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Animation/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Atmosphere/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Audio/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Camera/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Collision/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Commandlets/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Components/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Curves/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/DataDrivenCVars/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Debug/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/DeviceProfiles/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/EdGraph/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/EditorFramework/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Elements/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Engine/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/FieldNotification/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/GameFramework/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/HLOD/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/HLSLTree/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/InstancedStaticMesh/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Instances/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Internationalization/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/ISMPartition/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Kismet/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Layers/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/LevelInstance/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Materials/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/MeshMerge/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/MeshVertexPainter/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Misc/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Net/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/ODSC/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/PackedLevelActor/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/PacketHandlers/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Particles/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Performance/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/PhysicsEngine/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/PhysicsField/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/ProfilingDebugging/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Rendering/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Shader/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/ShaderCompiler/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Slate/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/SparseVolumeTexture/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Streaming/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Subsystems/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Tests/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/UniversalObjectLocators/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/UserInterface/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/Vehicles/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/VisualLogger/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/VT/*
ExcludePathFilters=%LOCENGINEROOT%Source/Runtime/Engine/Private/WorldPartition/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=Content/*
ExcludePathFilters=Content/Localization/*
ExcludePathFilters=Content/__ExternalActors__/*
ExcludePathFilters=Content/__ExternalObjects__/*
ExcludePathFilters=Content/Developers/*
ExcludePathFilters=Content/ZZ_ARCHIVE/*
ExcludePathFilters=Content/Art/Environment/Materials/*
ExcludePathFilters=Content/Art/Effects/Materials/*
ExcludePathFilters=Content/Art/Gameplay/Materials/*
ExcludePathFilters=Content/Art/VFX/Materials/*
ExcludePathFilters=Content/Editor/*
ExcludePathFilters=Content/Audio/Audio_Data/*
ExcludePathFilters=Content/Audio/Testing/*
ExcludePathFilters=Content/ThirdParty/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
ShouldExcludeDerivedClasses=false
ShouldGatherFromEditorOnlyData=false
SkipGatherCache=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive

[GatherTextStep4]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=Game.csv
bConflictReport=true
ConflictReportName=Game_Conflicts.txt

