// (c) 2018-2025 OtherSide Entertainment, Inc
// SPDX-License-Identifier: MIT
#include "Interactables/Electrical/TATPowerLine.h"

// tat
#include "Interactables/Electrical/TATPowerNetworkComponent.h"
#include "Interactables/Electrical/TATPowerNetworkSubsystem.h"

// ue
#include "AbilitySystemComponent.h"
#include "AbilitySystemGlobals.h"
#include "Components/StaticMeshComponent.h"
#include "Components/SplineComponent.h"
#include "Components/CapsuleComponent.h"
#include "GameFramework/Character.h"
#include "GameFramework/CharacterMovementComponent.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(TATPowerLine)

ATATPowerLine::ATATPowerLine()
{
   PrimaryActorTick.bCanEverTick = true;

   bReplicates = true;
   NetDormancy = DORM_Initial;

   SplineComponent = CreateDefaultSubobject<USplineComponent>(TEXT("SplineComponent"));
   RootComponent = SplineComponent;

   PowerNetworkComponent = CreateDefaultSubobject<UTATPowerNetworkComponent>(TEXT("PowerNetworkComponent"));
   PowerNetworkComponent->PowerNetworkRole = ETATPowerNetworkRole::Connector;
}

void ATATPowerLine::OnConstruction(const FTransform& transform)
{
   Super::OnConstruction(transform);

   if (AutoApplySplineCableSimulation)
   {
      RunCableSimulationAndApplyToSpline();
   }

   if (UseSplineMesh)
   {
      UTATSplineUtilities::AutoGenerateSplineMeshComponents(SplineComponent, SplineMesh);
   }
   else
   {
      UTATSplineUtilities::DestroyAllAutoGeneratedSplineMeshComponents(SplineComponent);
   }
}

void ATATPowerLine::BeginPlay()
{
   UTATSplineUtilities::ForEachAutoGeneratedSplineMeshComponent(SplineComponent,
      [this](USplineMeshComponent* splineMeshComponent)
      {
         check(splineMeshComponent != nullptr);
         splineMeshComponent->SetNotifyRigidBodyCollision(true);

         // Let blueprints configure the spline mesh components if needed
         OnSetupAutoGeneratedSplineMeshComponent(splineMeshComponent);
      });

   PowerNetworkComponent->OnPowerSurgeChanged.AddUniqueDynamic(this, &ATATPowerLine::_OnPowerSurgeChanged);

   Super::BeginPlay();
}

void ATATPowerLine::EndPlay(const EEndPlayReason::Type reason)
{
   PowerNetworkComponent->OnPowerSurgeChanged.RemoveAll(this);

   Super::EndPlay(reason);
}

void ATATPowerLine::Tick(float deltaSeconds)
{
   Super::Tick(deltaSeconds);

   if (_charactersOnPowerLine.IsEmpty())
   {
      return;
   }

   // Make sure the characters walking on this power line are still walking on it
   TArray<ACharacter*, TInlineAllocator<8>> removeCharacters;
   for (ACharacter* character : _charactersOnPowerLine)
   {
      if (!ensure(character != nullptr))
      {
         continue;
      }

      if (UCharacterMovementComponent* cmc = character->GetCharacterMovement())
      {
         UPrimitiveComponent* movementBase = cmc->GetMovementBase();
         if (movementBase == nullptr || movementBase->GetOwner() != this)
         {
            removeCharacters.Add(character);
         }
      }
   }

   // Trigger the relevant events for any characters that were on the power line and are now gone
   if (!removeCharacters.IsEmpty())
   {
      _charactersOnPowerLine.RemoveAll([&removeCharacters](ACharacter* character)
      {
         return removeCharacters.Contains(character);
      });

      for (ACharacter* character : removeCharacters)
      {
         _RemovePowerLineGameplayTags(character);

         OnCharacterStopTouchingPowerLine(character);

         // If this character had _StartPowerSurge called on it, call the inverse now
         _EndPowerSurge(character);
      }
   }
}

void ATATPowerLine::NotifyHit(UPrimitiveComponent* comp, AActor* otherActor, UPrimitiveComponent* otherComp, bool selfMoved, FVector hitLocation, FVector hitNormal, FVector normalImpulse, const FHitResult& hitResult)
{
   USplineMeshComponent* splineMeshComponent = Cast<USplineMeshComponent>(comp);
   if (splineMeshComponent == nullptr)
   {
      return;
   }

   const float nearestSplineInputKey = SplineComponent->FindInputKeyClosestToWorldLocation(hitLocation);

   ACharacter* character = Cast<ACharacter>(otherActor);
   if (character != nullptr && !_charactersOnPowerLine.Contains(character))
   {
      UE_LOG(LogTATPowerNetwork, Verbose, TEXT("ATATPowerLine::NotifyHit self=%s, comp=%s, otherActor=%s"), *GetNameSafe(this), *GetNameSafe(comp), *GetNameSafe(otherActor));

      _charactersOnPowerLine.Add(character);
      _AddPowerLineGameplayTags(character);
      OnCharacterStartTouchingPowerLine(character, nearestSplineInputKey);

      // If a power surge is currently active, immediately apply any power surge effects
      if (PowerNetworkComponent->IsPowerSurgeActive())
      {
         _StartPowerSurge(character);
      }
   }

   Super::NotifyHit(comp, otherActor, otherComp, selfMoved, hitLocation, hitNormal, normalImpulse, hitResult);
}

TOptional<FVector> ATATPowerLine::GetPowerNetworkWorldLocationForConnectionIndex(int32 index, bool forDebugVis) const
{
   // for debug visualizations, push the location back a bit to make it easier to distinguish the debug vis from the art
   static constexpr float debugVisRelativeOffset = 0.04f;

   if (index == 0)
   {
      static constexpr float baseLocation = 0.0f;
      return GetPowerLineWorldLocation(forDebugVis ? (baseLocation + debugVisRelativeOffset) : baseLocation);
   }
   if (index == 1)
   {
   static constexpr float baseLocation = 1.0f;
      return GetPowerLineWorldLocation(forDebugVis ? (baseLocation - debugVisRelativeOffset) : baseLocation);
   }
   return NullOpt;
}

void ATATPowerLine::OnCharacterBeginBasing_Implementation(ACharacter* character)
{
   if (!ensure(character != nullptr))
   {
      return;
   }

   if (_charactersOnPowerLine.Contains(character))
   {
      return;
   }

   UE_LOG(LogTATPowerNetwork, Verbose, TEXT("ATATPowerLine::OnCharacterBeginBasing_Implementation self=%s, character=%s"), *GetNameSafe(this), *GetNameSafe(character));

   _charactersOnPowerLine.Add(character);

   _AddPowerLineGameplayTags(character);

   OnCharacterStartTouchingPowerLine(character, SplineComponent->FindInputKeyClosestToWorldLocation(character->GetActorLocation()));

   // If a power surge is currently active, immediately apply any power surge effects
   if (PowerNetworkComponent->IsPowerSurgeActive())
   {
      _StartPowerSurge(character);
   }
}

void ATATPowerLine::RunCableSimulationAndApplyToSpline()
{
   FVector startLoc = FVector::ZeroVector;
   FVector endLoc = FVector::ZeroVector;
   if (!GetCableSimulationStartAndEnd(startLoc, endLoc) || FVector::DistSquared(startLoc, endLoc) <= 0.01f)
   {
      return;
   }

   static constexpr bool fixedEndpoints = true;
   static constexpr bool updateSpline = true;
   TArray<FTATCablePoint> cablePoints;
   UTATSplineUtilities::SetupSplineComponentWithCableSimulation(SplineComponent, startLoc, endLoc, CableSimulationSettings, cablePoints, ESplineCoordinateSpace::World,
      CableTension, CableMassPerMeter, CableNumCenterPoints, fixedEndpoints, fixedEndpoints, CableSimulationTimeSeconds, CableSimulationStepsPerSecond, updateSpline);

#if WITH_EDITOR
   // This is just here to make sure the spline mesh components get updated correctly when this function is called via editor button (CallInEditor)
   if (UseSplineMesh && GetWorld() && (GetWorld()->IsEditorWorld() && !GetWorld()->IsGameWorld()))
   {
      UTATSplineUtilities::AutoGenerateSplineMeshComponents(SplineComponent, SplineMesh);
   }
#endif
}

bool ATATPowerLine::GetCableSimulationStartAndEnd_Implementation(FVector& startLocation, FVector& endLocation) const
{
   AActor* actor0 = nullptr;
   AActor* actor1 = nullptr;
   if (!PowerNetworkComponent->GetActorConnectedToLinkSlot(0, actor0) || !PowerNetworkComponent->GetActorConnectedToLinkSlot(1, actor1))
   {
      startLocation = FVector::ZeroVector;
      endLocation = FVector::ZeroVector;
      return false;
   }

   auto getLinkLocation = [this](AActor* actor, FVector& outLoc) -> bool
   {
      if (actor == nullptr)
      {
         outLoc = FVector::ZeroVector;
         return false;
      }
      if (UTATPowerNetworkComponent* actorPowerNetworkComponent = UTATPowerNetworkComponent::GetPowerNetworkComponent(actor))
      {
         if (actorPowerNetworkComponent->GetWorldLocationForLinkedActor(this, outLoc))
         {
            return true;
         }
         if (actorPowerNetworkComponent->GetWorldLocationForConnectorIndex(0, outLoc))
         {
            return true;
         }
      }
      outLoc = actor->GetActorLocation();
      return true;
   };

   return getLinkLocation(actor0, startLocation) && getLinkLocation(actor1, endLocation);
}

void ATATPowerLine::OnSetupAutoGeneratedSplineMeshComponent_Implementation(USplineMeshComponent* splineMeshComponent)
{

}

void ATATPowerLine::OnCharacterStartTouchingPowerLine_Implementation(ACharacter* character, float nearestSplineInputKey)
{

}

void ATATPowerLine::OnCharacterStopTouchingPowerLine_Implementation(ACharacter* character)
{

}

FVector ATATPowerLine::GetPowerLineWorldLocation(float normalizedLocation) const
{
   check(SplineComponent != nullptr);
   if (SplineComponent->GetNumberOfSplinePoints() < 2)
   {
      return GetActorLocation();
   }
   const float splineDistance = FMath::Clamp(normalizedLocation, 0.0f, 1.0f) * SplineComponent->GetSplineLength();
   return SplineComponent->GetLocationAtDistanceAlongSpline(splineDistance, ESplineCoordinateSpace::World);
}

float ATATPowerLine::GetPowerLineLength() const
{
   check(SplineComponent != nullptr);
   if (SplineComponent->GetNumberOfSplinePoints() < 2)
   {
      return 0.0f;
   }
   return SplineComponent->GetSplineLength();
}

bool ATATPowerLine::FindSplineInputKeyForCharacterOnPowerLine(ACharacter* character, float& splineInputKey) const
{
   if (character == nullptr)
   {
      splineInputKey = 0.0f;
      return false;
   }

   splineInputKey = SplineComponent->FindInputKeyClosestToWorldLocation(character->GetActorLocation());
   return _charactersOnPowerLine.Contains(character);
}

void ATATPowerLine::_AddPowerLineGameplayTags(ACharacter* character)
{
   if (StandingOnPowerLineGameplayTag.IsValid())
   {
      if (UAbilitySystemComponent* asc = UAbilitySystemGlobals::GetAbilitySystemComponentFromActor(character))
      {
         asc->AddLooseGameplayTag(StandingOnPowerLineGameplayTag);
      }
   }
}

void ATATPowerLine::_RemovePowerLineGameplayTags(ACharacter* character)
{
   if (StandingOnPowerLineGameplayTag.IsValid())
   {
      if (UAbilitySystemComponent* asc = UAbilitySystemGlobals::GetAbilitySystemComponentFromActor(character))
      {
         asc->RemoveLooseGameplayTag(StandingOnPowerLineGameplayTag);
      }
   }
}

void ATATPowerLine::_StartPowerSurge(ACharacter* character)
{
   if (character == nullptr || _charactersAffectedByPowerSurge.Contains(character))
   {
      return;
   }

   _charactersAffectedByPowerSurge.Add(character);

   if (HasAuthority() && PowerSurgeGameplayEffect)
   {
      _AuthorityApplyPowerSurge(character);
   }
}

void ATATPowerLine::_EndPowerSurge(ACharacter* character)
{
   if (character == nullptr || !_charactersAffectedByPowerSurge.Contains(character))
   {
      return;
   }

   if (HasAuthority() && PowerSurgeGameplayEffect)
   {
      _AuthorityRemovePowerSurge(character);
   }

   _charactersAffectedByPowerSurge.Remove(character);
}

void ATATPowerLine::_AuthorityApplyPowerSurge(ACharacter* character)
{
   check(HasAuthority());
   if (character == nullptr || !PowerSurgeGameplayEffect)
   {
      return;
   }

   UAbilitySystemComponent* asc = UAbilitySystemGlobals::GetAbilitySystemComponentFromActor(character);
   if (asc == nullptr)
   {
      return;
   }

   FActiveGameplayEffectHandle* existingHandle = _powerSurgeEffectHandles.Find(character);
   if (existingHandle != nullptr && asc->GetActiveGameplayEffect(*existingHandle) != nullptr)
   {
      // We already have an active effect
      return;
   }

   const float splineInputKey = SplineComponent->FindInputKeyClosestToWorldLocation(character->GetActorLocation());
   const FVector splineLocation = SplineComponent->GetLocationAtSplineInputKey(splineInputKey, ESplineCoordinateSpace::World);
   const FVector splineRightVector = SplineComponent->GetRightVectorAtSplineInputKey(splineInputKey, ESplineCoordinateSpace::World);

   auto pointOnTraceLine = [&](float distance) -> FVector
   {
      return splineLocation + (FVector::UpVector * 50.0f) - (splineRightVector * distance);
   };

   FHitResult fakeHitResult{};
   fakeHitResult.Init();
   fakeHitResult.bBlockingHit = true;
   fakeHitResult.TraceStart = pointOnTraceLine(300.0f);
   fakeHitResult.TraceEnd = pointOnTraceLine(-300.0f);
   fakeHitResult.Location = pointOnTraceLine(30.0f);
   fakeHitResult.ImpactPoint = fakeHitResult.Location;
   fakeHitResult.HitObjectHandle = FActorInstanceHandle(character);
   fakeHitResult.Component = TWeakObjectPtr<UPrimitiveComponent>(character->GetCapsuleComponent());
   fakeHitResult.Distance = FVector::Distance(fakeHitResult.TraceStart, fakeHitResult.Location);
   fakeHitResult.Time = fakeHitResult.Distance / FVector::Distance(fakeHitResult.TraceStart, fakeHitResult.TraceEnd);
   fakeHitResult.Normal = (fakeHitResult.Location - fakeHitResult.TraceStart).GetSafeNormal();
   fakeHitResult.ImpactNormal = fakeHitResult.Normal;

   FGameplayEffectContextHandle effectContext = asc->MakeEffectContext();
   effectContext.AddOrigin(fakeHitResult.Location);
   effectContext.AddHitResult(fakeHitResult);
   effectContext.AddSourceObject(this);
   FActiveGameplayEffectHandle effectHandle = asc->ApplyGameplayEffectToSelf(PowerSurgeGameplayEffect.GetDefaultObject(), 0.0f, effectContext, FPredictionKey());
   if (effectHandle.IsValid())
   {
      _powerSurgeEffectHandles.Add(character, effectHandle);
   }
}

void ATATPowerLine::_AuthorityRemovePowerSurge(ACharacter* character)
{
   check(HasAuthority());
   if (character == nullptr || !PowerSurgeGameplayEffect)
   {
      return;
   }

   UAbilitySystemComponent* asc = UAbilitySystemGlobals::GetAbilitySystemComponentFromActor(character);
   if (asc == nullptr)
   {
      return;
   }

   FActiveGameplayEffectHandle* effectHandle = _powerSurgeEffectHandles.Find(character);
   if (effectHandle == nullptr)
   {
      return;
   }

   asc->RemoveActiveGameplayEffect(*effectHandle, PowerSurgeGameplayEffectStacksToRemove);
   _powerSurgeEffectHandles.Remove(character);
}

void ATATPowerLine::_OnPowerSurgeChanged(bool powerSurgeEnabled)
{
   if (powerSurgeEnabled)
   {
      for (ACharacter* character : _charactersOnPowerLine)
      {
         _StartPowerSurge(character);
      }
   }
   else
   {
      for (ACharacter* character : _charactersOnPowerLine)
      {
         _EndPowerSurge(character);
      }
   }
}
