// Copyright Epic Games, Inc. All Rights Reserved.
// (c) 2026 OtherSide Entertainment, Inc
// SPDX-License-Identifier: LicenseRef-Unreal-Engine-EULA AND MIT


#pragma once

#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/UObjectGlobals.h"
#include "UObject/Object.h"
#include "Templates/SubclassOf.h"
#include "OSEPerceptionTypes.h"
#include "OSESense.h"
#include "OSESenseConfig.generated.h"

class FGameplayDebuggerCategory;
class UOSEPerceptionComponent;

UCLASS(ClassGroup = AI, abstract, EditInlineNew, config=Game)
class OSEPERCEPTION_API UOSESenseConfig : public UObject
{
	GENERATED_BODY()

protected:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = Sense, AdvancedDisplay)
	FColor DebugColor;

	/** specifies age limit after stimuli generated by this sense become forgotten. 0 means "never" */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = Sense, meta = (ClampMin = "0.0", UIMin = "0.0"))
	float MaxAge;

	/** determines whether given sense starts in an enabled state */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = Sense)
	uint32 bStartsEnabled : 1;
	
	// name of sense
	mutable FString CachedSenseName;

public:
	UOSESenseConfig(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get());

	virtual TSubclassOf<UOSESense> GetSenseImplementation() const;

	FOSESenseID GetSenseID() const;
	FString GetSenseName() const;
	FColor GetDebugColor() const { return DebugColor; }
	void SetMaxAge(const float NewMaxAge) { MaxAge = NewMaxAge; }
	float GetMaxAge() const { return MaxAge == 0.f ? FOSEStimulus::NeverHappenedAge : MaxAge; }	
	bool IsEnabled() const { return bStartsEnabled; }

#if WITH_GAMEPLAY_DEBUGGER
	virtual void DescribeSelfToGameplayDebugger(const UOSEPerceptionComponent* PerceptionComponent, FGameplayDebuggerCategory* DebuggerCategory) const;
#endif // WITH_GAMEPLAY_DEBUGGER
};
