// (c) 2018-2023 OtherSide Entertainment, Inc
// SPDX-License-Identifier: MIT

#pragma once

// ue
#include "Math/Vector2D.h"
#include "Subsystems/WorldSubsystem.h"
#include "UObject/SoftObjectPtr.h"
#include "UObject/WeakObjectPtrTemplates.h"

#include "TATWorldMapSubsystem.generated.h"

struct FTATMapRepresentationData;
struct FGameplayTag;
class UTATMapActorComponent;
class ATATWorldMapBoundary;
class ATATPlayerController;

USTRUCT(BlueprintType)
struct TAT_API FTATActiveMapInfo
{
   GENERATED_BODY()

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Active Map Entry")
   TObjectPtr<ATATWorldMapBoundary> MapBoundary;

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Active Map Entry")
   FText Label;

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Active Map Entry")
   TSoftObjectPtr<UTexture2D> Texture;

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Active Map Entry")
   TSoftObjectPtr<UMaterialInterface> Material;

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Active Map Entry")
   FVector2D AnchorTopLeft = FVector2D(0, 0);

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Active Map Entry")
   FVector2D AnchorBottomRight = FVector2D(2048, 2048);

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Active Map Entry")
   bool IsAutoGenerated = false;

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Active Map Entry")
   TObjectPtr<UTexture> AutoGeneratedTexture;
};

UCLASS()
class TAT_API UTATWorldMapSubsystem : public UWorldSubsystem
{
   GENERATED_BODY()

   // From USubsystem
   virtual bool ShouldCreateSubsystem(UObject* outer) const override;

public:
   /// Gets the number of registered maps in the current level
   UFUNCTION(BlueprintPure, Category = "World Map Subsystem")
   int32 GetNumMaps() const;

   /// Gets the world map boundary actor that corresponds to the specified registered map index
   UFUNCTION(BlueprintPure, Category = "World Map Subsystem")
   ATATWorldMapBoundary* GetMapBoundaryActor(int32 mapIndex) const;

   ATATWorldMapBoundary* GetCurrentWorldMapBoundaryActor() const;

   /// Gets the player-facing label for the specified map index. Intended for UI display.
   UFUNCTION(BlueprintPure, Category = "World Map Subsystem")
   FText GetMapLabel(int32 mapIndex) const;

   /// Gets the index of the currently visible map
   UFUNCTION(BlueprintPure, Category = "World Map Subsystem")
   int32 GetCurrentMapIndex() const;
   
   /// Gets the index of the map that would be visible if no override was set (the map that represents where the player currently is)
   UFUNCTION(BlueprintPure, Category = "World Map Subsystem")
   int32 GetMapIndexForCurrentPlayerLocation() const;

   /// If a map override is set, returns it. Otherwise returns -1.
   UFUNCTION(BlueprintCallable, Category = "World Map Subsystem")
   bool GetMapIndexOverride(int32& overrideIndex) const;

   /// Sets an override map to view. Call ClearMapBoundaryActorIndexOverride to clear the override.
   /// Intended to allow players to change which map is visible in the map tool.
   UFUNCTION(BlueprintCallable, Category = "World Map Subsystem")
   void SetMapIndexOverride(int32 newIndex);

   /// Clears any override set via SetMapBoundaryActorIndexOverride and restores default behavior (auto-switch maps when moving between areas)
   UFUNCTION(BlueprintCallable, Category = "World Map Subsystem")
   void ClearMapIndexOverride();

   /// Can be called when the map tool is initialized to set up initial state for the auto-selected map.
   /// Only required when spawning the player inside a secondary map boundary actor (but safe to always call).
   UFUNCTION(BlueprintCallable, Category = "World Map Subsystem")
   void InitAutoSelectedMap(FVector playerLocation);

   UFUNCTION(BlueprintPure, Category = "World Map Subsystem")
   bool GetWorldMapMaterialAndAnchors(TSoftObjectPtr<UTexture2D>& texture, TSoftObjectPtr<UMaterialInterface>& material, FVector2D& anchorTopLeft, FVector2D& anchorBottomRight, bool& isAutoGenerated) const;

   UFUNCTION(BlueprintCallable, Category = "World Map Subsystem")
   UTexture* GetAutoGeneratedWorldMapTexture(bool forceUpdate = false);

   /// Retrieves metadata for the specified map.
   /// If mapIndex is -1, returns metadata for the currently visible map.
   /// If forceUpdateIfAutoGenerated is true and the returned map is auto-generated, re-renders the map to its render target.
   UFUNCTION(BlueprintCallable, Category = "World Map Subsystem")
   bool GetMapInfo(FTATActiveMapInfo& mapInfo, int32 mapIndex = -1, bool forceUpdateIfAutoGenerated = false);

   // Registers a map actor for tracking on the map screen, notifying listeners via OnMapActorRegistered
   void RegisterMapActor(UTATMapActorComponent* mapActorComponent);
   
   // Unregisters a map actor for tracking on the map screen, notifying listeners via OnMapActorUnregistered
   void UnregisterMapActor(UTATMapActorComponent* mapActorComponent);

   // This function is anti-thetical to the current implementation of this class...
   // because it gives the subsystem control over whether actors should be removed from the map
   // But in practice, the actors themselves should be in control of that
   // TODO: Rework this functionality so that the actors are removing themselves from the map instead of the subsystem removing the actors.
   // Unregisters all map actors whose current map sprite entry matches the spriteTag
   void UnregisterAllMapActorsWithSpriteTag(const FGameplayTag spriteTag);
   
   bool IsMapActorRegistered(UTATMapActorComponent* mapActorComponent) const;

   DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnMapActorChanged, const UTATMapActorComponent*, mapActorComponent);
   FOnMapActorChanged OnMapActorRegistered;
   UPROPERTY(BlueprintAssignable, Category = "World Map Subsystem")
   FOnMapActorChanged OnMapActorUnregistered;

   // Called when a map actor's state change requires a visual refresh
   FOnMapActorChanged OnMapActorChanged;

   DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FMapChangeEvent, int32, mapIndex, ATATWorldMapBoundary*, mapBoundaryActor);

   /// Called when the map boundary changes and a different map should be displayed
   UPROPERTY(BlueprintAssignable, Category = "World Map Subsystem")
   FMapChangeEvent OnActiveMapChanged;

   /// Called when the map index override changes - eg. when the player selects a different map to view.
   /// This is distinct from OnActiveMapChanged to allow the UI to distinguish between auto mode and override mode.
   UPROPERTY(BlueprintAssignable, Category = "World Map Subsystem")
   FMapChangeEvent OnMapIndexOverrideChanged;
   
   /// Called when the player moves between areas that have different maps (ignores overrides).
   /// This is useful to show which map the player is currently on regardless of which map is currently visible.
   UPROPERTY(BlueprintAssignable, Category = "World Map Subsystem")
   FMapChangeEvent OnMapIndexForPlayerLocationChanged;

   // Should be called whenever a UTATMapActorComponent's state is changed in a way that should reflect in the UI
   void BroadcastMapActorChange(const UTATMapActorComponent* mapActorComponent);

   UFUNCTION(BlueprintPure, Category = "Map Screen", Meta = (WorldContext = "contextObject"))
   static FVector2D ConvertWorldLocationToMapLocation(const UObject* contextObject, const FVector& worldLocation, const FTATMapRepresentationData& mapRepresentationData, const FVector2D& mapDimensions, const FVector2D& mapOffset = FVector2D::ZeroVector);
   static float ConvertMapDistanceToSlateDistance(const UObject* contextObject, float mapDistance, const FVector2D& mapDimensions);

   const TSet<TWeakObjectPtr<UTATMapActorComponent>>& GetMapRepresentedActors() const { return _mapRepresentedActors; }

   void RegisterMapBoundary(ATATWorldMapBoundary* mapBoundaryActor);
   void UnregisterMapBoundary(ATATWorldMapBoundary* mapBoundaryActor);

   TSoftObjectPtr<UTextureRenderTarget2D> GetRenderTargetForAutoGeneratedMap(ATATWorldMapBoundary* mapBoundaryActor);

   void NotifyLocalPlayerInteriorMapBeginOverlap(ATATWorldMapBoundary* mapBoundary, ATATPlayerController* pc);
   void NotifyLocalPlayerInteriorMapEndOverlap(ATATWorldMapBoundary* mapBoundary, ATATPlayerController* pc);

private:
   int32 _FindRegisteredMapIndex(ATATWorldMapBoundary* mapBoundary) const;
   ATATWorldMapBoundary* _GetCurrentWorldMapBoundaryActor(int32* outIndex = nullptr) const;

   TSet<TWeakObjectPtr<UTATMapActorComponent>> _mapRepresentedActors;

   struct FRegisteredMap
   {
      TWeakObjectPtr<ATATWorldMapBoundary> BoundaryActor;
      FBox Bounds;
      FText Label;
      bool IsPrimary = false;
      int32 RenderTargetIndex = INDEX_NONE; // Only used for auto-generated maps
   };
   /// Array of all ATATWorldMapBoundary actors in the level
   TArray<FRegisteredMap> _registeredMaps;

   /// Player-overridable registered map index. Used to allow players to select which map to view on the in-game map tool.
   /// If set to INDEX_NONE, uses _activeMapStack to auto-select a map.
   int32 _activeMapIndexOverride = INDEX_NONE;

   /// The registered map index of the primary map for the current level.
   int32 _primaryMapIndex = INDEX_NONE;

   /// A stack of registered map indices, used for auto-selecting the map to show.
   /// Anytime the player enters a map volume, it's added to this stack, and when they leave a map volume it's removed.
   TArray<int32> _activeMapStack;

   void _NotifyActiveMapChanged(int32 newIndex);
   void _NotifyMapIndexOverrideChanged(int32 newIndex);
   void _NotifyMapIndexForPlayerLocationChanged(int32 newIndex);

   /// Stack based active map tracker for detecting map changes in functions and calling
   /// _NotifyActiveMapChanged() when a method results in the current map changing.
   class FActiveMapChangeTracker
   {
      UTATWorldMapSubsystem* MapSubsystem;
      int32 PrevOverrideIndex;
      int32 PrevIndex;
      int32 PrevIndexForPlayerLocation;

   public:
      explicit FActiveMapChangeTracker(UTATWorldMapSubsystem* mapSubsystem)
         : MapSubsystem(mapSubsystem)
         , PrevOverrideIndex(mapSubsystem->_activeMapIndexOverride)
         , PrevIndex(mapSubsystem->GetCurrentMapIndex())
         , PrevIndexForPlayerLocation(mapSubsystem->GetMapIndexForCurrentPlayerLocation())
      {
      }

      ~FActiveMapChangeTracker()
      {
         if (MapSubsystem->_activeMapIndexOverride != PrevOverrideIndex)
         {
            MapSubsystem->_NotifyMapIndexOverrideChanged(MapSubsystem->_activeMapIndexOverride);
         }
         const int32 nextIndex = MapSubsystem->GetCurrentMapIndex();
         if (PrevIndex != nextIndex)
         {
            MapSubsystem->_NotifyActiveMapChanged(nextIndex);
         }
         const int32 nextPlayerLocIndex = MapSubsystem->GetMapIndexForCurrentPlayerLocation();
         if (PrevIndexForPlayerLocation != nextPlayerLocIndex)
         {
            MapSubsystem->_NotifyMapIndexForPlayerLocationChanged(nextPlayerLocIndex);
         }
      }
   };
};
