// (c) 2018-2023 OtherSide Entertainment, Inc
// SPDX-License-Identifier: MIT

#pragma once

// ue
#include "GameFramework/Actor.h"

#include "TATWorldMapBoundary.generated.h"

class UBoxComponent;

UENUM(BlueprintType)
enum class ETATWorldMapBoundaryType : uint8
{
   Primary = 0,
   Secondary,
};

USTRUCT(BlueprintType)
struct TAT_API FTATWorldMapAutoSwitchBounds
{
   GENERATED_BODY()

   UPROPERTY(BlueprintReadWrite, EditAnywhere)
   FVector OriginOffset = FVector::ZeroVector;

   /// If enabled, treat the extent as a proportion of the boundary extent (1.0 means the size of the boundary)
   UPROPERTY(BlueprintReadWrite, EditAnywhere)
   bool UseRelativeExtent = true;

   /// If enabled, take the map's aspect ratio into account when computing the size
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Meta = (EditCondition = "UseRelativeExtent", EditConditionHides))
   bool ApplyAspectRatio = true;

   UPROPERTY(BlueprintReadWrite, EditAnywhere)
   FVector Extent = FVector(0.99f, 0.99f, 0.99f);

   FVector GetRelativeLocation(const FVector& scale) const;
   FVector GetRelativeExtent(const FVector& scale, float aspectRatio) const;
};

// An actor intended for designers to position a bounding box around the level, 
// corresponding to the boundaries of the map image shown on the Management Screen.
UCLASS()
class TAT_API ATATWorldMapBoundary : public AActor
{
   GENERATED_BODY()

   ATATWorldMapBoundary(const FObjectInitializer& objectInitializer);

public:
   virtual void OnConstruction(const FTransform& transform) override;
   virtual void BeginPlay() override;
   virtual void EndPlay(const EEndPlayReason::Type endPlayReason) override;

   FVector2D GetUnscaledBoundaryExtents() const;

   /// Player-facing label for this map
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary")
   FText MapLabel;

   /// Is this map boundary a primary (the whole level) or secondary area (eg. an interior or other sub-area of the level)
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary")
   ETATWorldMapBoundaryType MapType = ETATWorldMapBoundaryType::Primary;

   /// Should the in-game map tool auto-switch to this map when the player enters it's volume?
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary", Meta = (EditCondition = "MapType == ETATWorldMapBoundaryType::Secondary", EditConditionHides))
   bool AutoSwitchToMap = true;

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary", Meta = (EditCondition = "MapType == ETATWorldMapBoundaryType::Secondary && AutoSwitchToMap", EditConditionHides))
   FTATWorldMapAutoSwitchBounds AutoSwitchBounds;

   /// Map material used when showing the map on the in-game map tool
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary")
   TSoftObjectPtr<UMaterialInterface> MapMaterial;

   /// Map texture used when showing the map in the UI
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary")
   TSoftObjectPtr<UTexture2D> MapTexture;

   /// The point (in texture-space) on the map texture that corresponds to the top left corner of the map boundary.
   /// This defines how world coordinates are mapped to texture coordinates.
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary")
   FVector2D MapTextureAnchorTopLeft = FVector2D(0, 0);

   /// The point (in texture-space) on the map texture that corresponds to the bottom right corner of the map boundary
   /// This defines how world coordinates are mapped to texture coordinates.
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary")
   FVector2D MapTextureAnchorBottomRight = FVector2D(2048, 2048);

   /// If no valid map material is assigned, auto-generate the map using a scene capture render target
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary|Auto-Generated Map")
   bool AutoGenerateMapIfMissingMapMaterial = true;

   /// Always auto-generate the map, even if we have a valid map material
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary|Auto-Generated Map")
   bool ForceAutoGenerateMap = false;

   /// If enabled, use different anchor points when an auto-generated map is used
   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary|Auto-Generated Map")
   bool UseAutoGeneratedMapAnchors = true;

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary|Auto-Generated Map", Meta = (EditCondition = "UseAutoGeneratedMapAnchors"))
   FVector2D AutoGeneratedMapAnchorTopLeft = FVector2D(128.0f, 384.0f);

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary|Auto-Generated Map", Meta = (EditCondition = "UseAutoGeneratedMapAnchors"))
   FVector2D AutoGeneratedMapAnchorBottomRight = FVector2D(1920.0f, 1728.0f);

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary|Auto-Generated Map")
   TEnumAsByte<ESceneCaptureSource> MapRenderTextureCaptureSource = SCS_BaseColor;

   UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "World Map Boundary|Auto-Generated Map")
   float MapRenderTextureHeightOffset = 0.0f;

   UFUNCTION(BlueprintPure, Category = "World Map Boundary")
   bool UseAutoGeneratedMap() const;

   UFUNCTION(BlueprintCallable, Category = "World Map Boundary")
   UTexture* GetAutoGeneratedMapTexture(bool forceUpdate = false);

   UFUNCTION(BlueprintPure, Category = "World Map Boundary")
   TSoftObjectPtr<UMaterialInterface> GetMapMaterial() const;

   UFUNCTION(BlueprintPure, Category = "World Map Boundary")
   void GetMapTextureAnchorPoints(FVector2D& outTopLeft, FVector2D& outBottomRight, bool normalized = false) const;

   UFUNCTION(BlueprintPure, Category = "World Map Boundary")
   FVector2D GetMapAreaRelativeSize() const;

   UFUNCTION(BlueprintPure, Category = "World Map Boundary")
   float GetMapAspectRatio() const;

   /// Gets the bounding box for the area of the level used for the player-facing map.
   UFUNCTION(BlueprintPure, Category = "World Map Boundary")
   FBox GetMapAreaBoundingBox() const;

   DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FMapTextureUpdateEvent, UTexture*, mapTexture, const FBox&, boundingBox, bool, textureUpdated);

   /// Event fired every time the map texture updates
   UPROPERTY(BlueprintAssignable, Category = "World Map Boundary")
   FMapTextureUpdateEvent OnUpdateMapTexture;

#if WITH_EDITOR
   virtual void PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent) override;

   UFUNCTION(CallInEditor, Category = "World Map Boundary")
   void UpdateMapRenderTarget();

   /// Exports the render target to a PNG file, taking aspect ratio into account.
   /// Note that the full path to the rendered image will be written to the output log.
   UFUNCTION(CallInEditor, Category = "World Map Boundary - Export Image")
   void ExportAutoGeneratedMapToImage();
#endif // WITH_EDITOR

#if WITH_EDITORONLY_DATA
   /// Exported image filename. If not specified, it will use the MapLabel field
   UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "World Map Boundary - Export Image")
   FString ExportImageFileName;

   /// If enabled, discards the render target's alpha channel and sets it to maximum (fully opaque) in the exported image
   UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "World Map Boundary - Export Image")
   bool ExportImage_RemoveAlphaChannel = false;

   /// If enabled (and remove alpha channel is false), inverts the alpha channel in the exported image
   UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "World Map Boundary - Export Image", Meta = (EditCondition = "!ExportImage_RemoveAlphaChannel"))
   bool ExportImage_InvertAlphaChannel = true;
#endif

private:
   void _UpdateMapTextureUsingRenderTarget(bool forceUpdate);

   UFUNCTION()
   void _OnBoxBeginOverlap(UPrimitiveComponent* overlappedComponent, AActor* otherActor, UPrimitiveComponent* otherComp, int32 otherBodyIndex, bool fromSweep, const FHitResult& sweepResult);
   UFUNCTION()
   void _OnBoxEndOverlap(UPrimitiveComponent* overlappedComponent, AActor* otherActor, UPrimitiveComponent* otherComp, int32 otherBodyIndex);

   UPROPERTY()
   TObjectPtr<UBoxComponent> _boxComponent;

   /// This component is used to detect players entering and exiting the map area when auto-switching is enabled
   UPROPERTY()
   TObjectPtr<UBoxComponent> _autoSwitchOverlapComponent;

#if WITH_EDITORONLY_DATA
   UPROPERTY()
   TObjectPtr<UBoxComponent> _mapBoundsPreviewComponent;
#endif

   UPROPERTY(EditDefaultsOnly, Category = "World Map Boundary")
   TObjectPtr<USceneCaptureComponent2D> _mapSceneCaptureComponent;

   /// Render target to use for the map
   UPROPERTY(Transient)
   TObjectPtr<UTextureRenderTarget2D> _mapRenderTarget;

   bool _mapRenderTargetCaptured = false;

#if WITH_EDITORONLY_DATA
   UPROPERTY(EditAnywhere, Category = "Editor Visualization")
   float _editorLineThickness = 10.f;
#endif // WITH_EDITORONLY_DATA
};
