; NOTE: Formerly disabled to address TOW-2589 (secondary upsample to output clears alpha)
; I no longer see this issue with bugit screenshots and secondary up-scale, so re-enabling it
;     The problem is actually due to the secondary temporal up-sample, which we only apply in game builds. Due to a likely bug in UE4 (and UE5) when outputting to the frame buffer, alpha is slammed to zero. Normally this is fine, but when the images are saved as PNG they are stored in premultiplied alpha format and color data is lost.
;     The likely engine mod is likely to pass EUpscaleStage as a shader permutation in ISpatialUpscaler::AddDefaultUpscalePass and skip the !POST_PROCESS_ALPHA block at the end of the PostProcessUpscale.usf shader if the upscale stage is EUpscaleStage::PrimaryToOutput or EUpscaleStage::SecondaryToOutput. It's also possible the !POST_PROCESS_ALPHA check isn't needed at all in the upsample shader, but I'm not familiar enough with that rendering flow to commit to that fix.
[Windows DeviceProfile]
+CVars=r.SecondaryScreenPercentage.GameViewport=90

[WindowsEditor DeviceProfile]
+CVars=r.Nanite.Visualize.Advanced=1
