[ScalabilitySettings]
; Bump this version to invalidate user scalability settings and run automated hardware benchmark
Version=1

; Min Spec GPU (GTX 1060) is ~165, and go up to ~300-400
; CPU benchmark values are much more constrained, only ~160 to ~200
; We expect the min-spec to run on low, and the recommended spec to run on high/very high
; Some settings like AA don't seem to affect perf much, so we should evaluate if it's worth setting them higher by default
PerfIndexThresholds_ResolutionQuality="GPU 170 220 320"
PerfIndexThresholds_ViewDistanceQuality="Min 170 180 200"
PerfIndexThresholds_ShadowQuality="GPU 170 220 320"
PerfIndexThresholds_GlobalIlluminationQuality="GPU 170 220 320"
PerfIndexThresholds_ReflectionQuality="GPU 170 220 320"
PerfIndexThresholds_PostProcessQuality="GPU 170 220 320"
PerfIndexThresholds_TextureQuality="GPU 170 220 320"
PerfIndexThresholds_EffectsQuality="Min 170 180 200"
PerfIndexThresholds_FoliageQuality="GPU 170 220 320"
PerfIndexThresholds_ShadingQuality="GPU 170 220 320"

; Corresponds to the following percentage of pixels by area: 25%, 44%, 50%, 56%
;  (UHD x 44% = QHD; QHD x 56% = FHD; FHD x 44% = HD)
PerfIndexValues_ResolutionQuality="50 67 71 75 100"

[ShadowQuality@0]
r.VolumetricFog=1
r.VolumetricFog.GridPixelSize=24
r.VolumetricFog.GridSizeZ=32
r.VolumetricFog.HistoryMissSupersampleCount=1
r.LightFunctionQuality=0
r.ShadowQuality=2
r.Shadow.CSM.MaxCascades=1
r.Shadow.MaxResolution=1024
r.Shadow.MaxCSMResolution=1024
r.Shadow.RadiusThreshold=0.05
r.Shadow.DistanceScale=0.7
r.Shadow.CSM.TransitionScale=0.25
r.Shadow.PreShadowResolutionFactor=0.5
r.DistanceFieldShadowing=0
r.LightMaxDrawDistanceScale=.4
r.Shadow.Virtual.MaxPhysicalPages=512
r.Shadow.Virtual.ResolutionLodBiasDirectional=2.0
r.Shadow.Virtual.ResolutionLodBiasDirectionalMoving=2.0
r.Shadow.Virtual.ResolutionLodBiasLocal=1.0
r.Shadow.Virtual.ResolutionLodBiasLocalMoving=2.0
r.Shadow.Virtual.SMRT.RayCountDirectional=2
r.Shadow.Virtual.SMRT.SamplesPerRayDirectional=2
r.Shadow.Virtual.SMRT.RayCountLocal=2
r.Shadow.Virtual.SMRT.SamplesPerRayLocal=2


[ShadowQuality@1]
r.VolumetricFog=1
r.VolumetricFog.GridPixelSize=16
r.VolumetricFog.GridSizeZ=64
r.VolumetricFog.HistoryMissSupersampleCount=2

[ShadowQuality@2]
r.VolumetricFog=1
r.VolumetricFog.GridPixelSize=8
r.VolumetricFog.GridSizeZ=64
r.VolumetricFog.HistoryMissSupersampleCount=4

[ShadowQuality@3]
r.VolumetricFog=1
r.VolumetricFog.GridPixelSize=8
r.VolumetricFog.GridSizeZ=128
r.VolumetricFog.HistoryMissSupersampleCount=4
r.Shadow.Virtual.ResolutionLodBiasDirectional=-0.5

[ShadowQuality@Cine]
r.VolumetricFog=1
r.VolumetricFog.GridPixelSize=4
r.VolumetricFog.GridSizeZ=128
r.VolumetricFog.HistoryMissSupersampleCount=16

[GlobalIlluminationQuality@0]
; turn on lumen for low
; for now, copied directly from BaseScalability for High, but with DirectLighting=0
r.Lumen.DiffuseIndirect.Allow=1
r.LumenScene.Radiosity.ProbeSpacing=8
r.LumenScene.Radiosity.HemisphereProbeResolution=3
r.Lumen.TraceMeshSDFs.Allow=0
r.Lumen.ScreenProbeGather.RadianceCache.ProbeResolution=16
r.Lumen.ScreenProbeGather.RadianceCache.NumProbesToTraceBudget=300
r.Lumen.ScreenProbeGather.DownsampleFactor=32
r.Lumen.ScreenProbeGather.TracingOctahedronResolution=8
r.Lumen.ScreenProbeGather.IrradianceFormat=1
r.Lumen.ScreenProbeGather.StochasticInterpolation=1
r.Lumen.ScreenProbeGather.FullResolutionJitterWidth=1
r.Lumen.ScreenProbeGather.TwoSidedFoliageBackfaceDiffuse=0
r.Lumen.ScreenProbeGather.ScreenTraces.HZBTraversal.FullResDepth=0
r.Lumen.Reflections.MaxRoughnessToTraceForFoliage=0.2
r.Lumen.TranslucencyVolume.GridPixelSize=64
r.Lumen.TranslucencyVolume.TraceFromVolume=0
r.Lumen.TranslucencyVolume.RadianceCache.ProbeResolution=8
r.Lumen.TranslucencyVolume.RadianceCache.NumProbesToTraceBudget=200
r.Lumen.TranslucencyVolume.TracingOctahedronResolution=3
r.LumenScene.DirectLighting=0 ; just turn it off

[GlobalIlluminationQuality@1]
; turn on lumen for medium
; for now, copied directly from BaseScalability for High (should see if there are cheaper settings)
r.Lumen.DiffuseIndirect.Allow=1
r.LumenScene.Radiosity.ProbeSpacing=8
r.LumenScene.Radiosity.HemisphereProbeResolution=3
r.Lumen.TraceMeshSDFs.Allow=0
r.Lumen.ScreenProbeGather.RadianceCache.ProbeResolution=16
r.Lumen.ScreenProbeGather.RadianceCache.NumProbesToTraceBudget=300
r.Lumen.ScreenProbeGather.DownsampleFactor=32
r.Lumen.ScreenProbeGather.TracingOctahedronResolution=8
r.Lumen.ScreenProbeGather.IrradianceFormat=1
r.Lumen.ScreenProbeGather.StochasticInterpolation=1
r.Lumen.ScreenProbeGather.FullResolutionJitterWidth=1
r.Lumen.ScreenProbeGather.TwoSidedFoliageBackfaceDiffuse=0
r.Lumen.ScreenProbeGather.ScreenTraces.HZBTraversal.FullResDepth=0
r.Lumen.Reflections.MaxRoughnessToTraceForFoliage=0.2
r.Lumen.TranslucencyVolume.GridPixelSize=64
r.Lumen.TranslucencyVolume.TraceFromVolume=0
r.Lumen.TranslucencyVolume.RadianceCache.ProbeResolution=8
r.Lumen.TranslucencyVolume.RadianceCache.NumProbesToTraceBudget=200
r.Lumen.TranslucencyVolume.TracingOctahedronResolution=3
r.LumenScene.DirectLighting=1
r.LumenScene.DirectLighting.UpdateFactor=64

[GlobalIlluminationQuality@2]
; This is the default value in code, but it is set to a different value in cinematic, which can leak when changing back
r.Lumen.TranslucencyVolume.TracingOctahedronResolution=3
r.LumenScene.DirectLighting=1
r.LumenScene.DirectLighting.UpdateFactor=64

[GlobalIlluminationQuality@3]
r.LumenScene.DirectLighting=1
r.LumenScene.DirectLighting.UpdateFactor=32

[GlobalIlluminationQuality@Cine]
r.LumenScene.DirectLighting=1
r.LumenScene.DirectLighting.UpdateFactor=32

[ReflectionQuality@0]
r.SSR.Quality=1 ; Without this, the interior is still weirldly bright even with lumen (not ideal to be separate, but don't want to mix)

;-----------------------------------------------------------------------------------------------------------------

; Compress distance scale upwards (starting at 0.6 rather than 0.4)
; so that distances can be tuned with relatively tight bounds on high
; without looking terrible on low. Will be measuring impact

[ViewDistanceQuality@0]
r.ViewDistanceScale=0.6

[ViewDistanceQuality@1]
r.ViewDistanceScale=0.7

[ViewDistanceQuality@2]
r.SkeletalMeshLODBias=0
r.ViewDistanceScale=0.8

[ViewDistanceQuality@3]
r.ViewDistanceScale=1.0

[ViewDistanceQuality@Cine]
r.ViewDistanceScale=1.0
