// (c) 2018-2025 OtherSide Entertainment, Inc
// SPDX-License-Identifier: MIT

#pragma once

#include <NativeGameplayTags.h>

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Audio);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Audio_MasterVolume);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Audio_MusicVolume);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Audio_EffectsVolume);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Audio_DialogueVolume);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_General);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_General_Language);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_General_AllowAnalytics);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_General_SprintToggle);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_General_ReducedCameraBounce);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_General_MouseSensitivityRel);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_General_MouseInvertYAxis);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_General_GamepadSensitivityRel);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_General_GamepadInvertYAxis);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_DisplayMonitor);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_WindowMode);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_Resolution);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_VSync);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_FOV);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_MotionBlur);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_FPSLimit);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_OverallQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_ResolutionQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_ViewDistanceQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_AntiAliasingQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_ShadowQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_GlobalIlluminationQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_ReflectionQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_PostProcessQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_TextureQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_EffectsQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_FoliageQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_ShadingQuality);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Settings_Video_LandscapeQuality);
