// (c) 2018-2023 OtherSide Entertainment, Inc
// SPDX-License-Identifier: MIT
#pragma once

// ue5
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_PRIVATESPACE_HOSTILEINTRUDER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_PRIVATESPACE_IDENTIFIEDINTRUDER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STATUS_PRIVATESPACE_INTRUDING)
